
  CREATE TABLE "AJC"."AJC_BC_ARXAGE_RPT_TEMP" 
   (	"CUSTOMER_ID" NUMBER, 
	"CUSTOMER_NUMBER" VARCHAR2(30), 
	"CUSTOMER_NAME" VARCHAR2(360), 
	"COUNTRY_NAME" VARCHAR2(35), 
	"OUTSTANDING_AMT" NUMBER, 
	"OVER_60DAYS_AMT" NUMBER, 
	"OA_AMT" NUMBER, 
	"SD_AMT" NUMBER, 
	"LC_AMT" NUMBER, 
	"COD_AMT" NUMBER, 
	"ONACCT_AMT" NUMBER, 
	"AIG_LIMIT" NUMBER, 
	"INSURED_AR" NUMBER, 
	"OAC_LIMIT" NUMBER, 
	"OAC_AVAILABLE_CURRENCY" VARCHAR2(15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_ARXAGE_RPT_TEMP" FOR "AJC"."AJC_BC_ARXAGE_RPT_TEMP"
