
  CREATE TABLE "AJC"."AJC_BC_ARXAGE" 
   (	"CUSTOMER_ID" NUMBER, 
	"CUSTOMER_NUMBER" VARCHAR2(30), 
	"CUSTOMER_NAME" VARCHAR2(50), 
	"INVOICE_NUMBER" VARCHAR2(20), 
	"TYPE" VARCHAR2(100), 
	"DUE_DATE" DATE, 
	"REFERENCE_NUMBER" VARCHAR2(100), 
	"DAYS_LATE" NUMBER, 
	"PERCENTAGE_UNPAID" NUMBER, 
	"ORIGINAL_AMOUNT" NUMBER, 
	"OUTSTANDING_AMOUNT" NUMBER, 
	"CURRENT_AMOUNT" NUMBER, 
	"DAYS_PAST_DUE_1_30" NUMBER, 
	"DAYS_PAST_DUE_31_60" NUMBER, 
	"DAYS_PAST_DUE_61_PLUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_ARXAGE_I1" ON "AJC"."AJC_BC_ARXAGE" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_ARXAGE_I4" ON "AJC"."AJC_BC_ARXAGE" ("INVOICE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_ARXAGE_I3" ON "AJC"."AJC_BC_ARXAGE" ("CUSTOMER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_ARXAGE_I2" ON "AJC"."AJC_BC_ARXAGE" ("CUSTOMER_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_ARXAGE" FOR "AJC"."AJC_BC_ARXAGE"
