
  CREATE TABLE "AJC"."AJC_BC_FA_FIXED_ASSETS" 
   (	"ASSET_ID" NUMBER, 
	"BOOK_TYPE_CODE" VARCHAR2(30), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"NO" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(200), 
	"SEARCH_DESCRIPTION" VARCHAR2(200), 
	"DESCRIPTION_2" VARCHAR2(200), 
	"FA_CLASS_CODE" VARCHAR2(100), 
	"FA_SUBCLASS_CODE" VARCHAR2(100), 
	"GLOBAL_DIMENSION_1_CODE" VARCHAR2(100), 
	"GLOBAL_DIMENSION_2_CODE" VARCHAR2(100), 
	"LOCATION_CODE" VARCHAR2(10), 
	"FA_LOCATION_CODE" VARCHAR2(10), 
	"VENDOR_NO" VARCHAR2(30), 
	"MAIN_ASSET_COMPONENT" VARCHAR2(100), 
	"COMPONENT_OF_MAIN_ASSET" VARCHAR2(100), 
	"BUDGETED_ASSET" VARCHAR2(100), 
	"WARRANTY_DATE" VARCHAR2(10), 
	"RESPONSIBLE_EMPLOYEE" VARCHAR2(100), 
	"SERIAL_NO" VARCHAR2(50), 
	"LAST_DATE_MODIFIED" VARCHAR2(10), 
	"BLOCKED" VARCHAR2(100), 
	"MAINTENANCE_VENDOR_NO" VARCHAR2(100), 
	"UNDER_MAINTENANCE" VARCHAR2(100), 
	"NEXT_SERVICE_DATE" VARCHAR2(100), 
	"INACTIVE" VARCHAR2(100), 
	"NO_SERIES" VARCHAR2(100), 
	"FA_POSTING_GROUP" VARCHAR2(100), 
	"IMAGE" VARCHAR2(100), 
	"VEHICLE_LICENSE_PLATE" VARCHAR2(100), 
	"VEHICLE_YEAR" NUMBER, 
	"SAT_FEDERAL_AUTOTRANSPORT" VARCHAR2(100), 
	"SAT_TRAILER_TYPE" VARCHAR2(100), 
	"SCT_PERMISSION_TYPE" VARCHAR2(100), 
	"SCT_PERMISSION_NUMBER" VARCHAR2(100), 
	"SAT_CLASSIFICATION_CODE" VARCHAR2(100), 
	"USCG_NO" VARCHAR2(100), 
	"ASSET_TAG" VARCHAR2(100), 
	"YEAR_OF_MANUFACTURE" VARCHAR2(100), 
	"VIN_NO" VARCHAR2(100), 
	"ENGINE_NO" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_FA_FIXED_ASSETS" FOR "AJC"."AJC_BC_FA_FIXED_ASSETS"
