
  CREATE TABLE "AJC"."AJC_BC_FA_FIXED_ASSETS_JOURNAL" 
   (	"ASSET_ID" NUMBER, 
	"BOOK_TYPE_CODE" VARCHAR2(30), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"JOURNAL_TEMPLATE_NAME" VARCHAR2(100), 
	"JOURNAL_BATCH_NAME" VARCHAR2(100), 
	"LINE_NO" NUMBER, 
	"DEPRECIATION_BOOK_CODE" VARCHAR2(100), 
	"FA_POSTING_TYPE" VARCHAR2(100), 
	"FA_NO" VARCHAR2(100), 
	"FA_POSTING_DATE" VARCHAR2(10), 
	"POSTING_DATE" VARCHAR2(100), 
	"DOCUMENT_TYPE" VARCHAR2(100), 
	"DOCUMENT_DATE" VARCHAR2(100), 
	"DOCUMENT_NO" VARCHAR2(100), 
	"EXTERNAL_DOCUMENT_NO" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(100), 
	"AMOUNT" NUMBER, 
	"DEBIT_AMOUNT" NUMBER, 
	"CREDIT_AMOUNT" NUMBER, 
	"SALVAGE_VALUE" NUMBER, 
	"QUANTITY" NUMBER, 
	"CORRECTION" VARCHAR2(100), 
	"NO_OF_DEPRECIATION_DAYS" NUMBER, 
	"DEPR_UNTIL_FA_POSTING_DATE" VARCHAR2(100), 
	"DEPR_ACQUISITION_COST" VARCHAR2(100), 
	"FA_POSTING_GROUP" VARCHAR2(100), 
	"MAINTENANCE_CODE" VARCHAR2(100), 
	"SHORTCUT_DIMENSION_1_CODE" VARCHAR2(100), 
	"SHORTCUT_DIMENSION_2_CODE" VARCHAR2(100), 
	"INSURANCE_NO" VARCHAR2(100), 
	"BUDGETED_FA_NO" VARCHAR2(100), 
	"USE_DUPLICATION_LIST" VARCHAR2(100), 
	"DUPLICATE_IN_DEPRECIATION_BOOK" VARCHAR2(100), 
	"FA_RECLASSIFICATION_ENTRY" VARCHAR2(100), 
	"FA_ERROR_ENTRY_NO" VARCHAR2(100), 
	"REASON_CODE" VARCHAR2(100), 
	"SOURCE_CODE" VARCHAR2(100), 
	"RECURRING_METHOD" VARCHAR2(100), 
	"RECURRING_FREQUENCY" VARCHAR2(100), 
	"EXPIRATION_DATE" VARCHAR2(100), 
	"INDEX_ENTRY" VARCHAR2(100), 
	"POSTING_NO_SERIES" VARCHAR2(100), 
	"DIMENSION_SET_ID" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_FA_FIXED_ASSETS_JOURNAL" FOR "AJC"."AJC_BC_FA_FIXED_ASSETS_JOURNAL"
