
  CREATE TABLE "AJC"."AJC_BC_INVOICES" 
   (	"DOCUMENT_NO" VARCHAR2(100) NOT NULL ENABLE, 
	"VENDOR_INV_NUMBER" VARCHAR2(500), 
	"INV_DATE" DATE, 
	"DUE_DATE" DATE, 
	"AMOUNT" NUMBER, 
	"AJC_ATTRIBUTE1" VARCHAR2(200), 
	"VENDOR_NUMBER" NUMBER, 
	"COMPANY_CODE" NUMBER, 
	"SYNC_COMPANY_ID" VARCHAR2(300), 
	"SYNC_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"CURRENCY_CODE" VARCHAR2(20), 
	"CREATED_DATE" DATE, 
	"CLOSED" VARCHAR2(10), 
	"DESCRIPTION_AJC" VARCHAR2(4000), 
	"STATUS" VARCHAR2(100), 
	"VENDORCATEG" VARCHAR2(200), 
	"TRAFFICOORD" VARCHAR2(200), 
	"NOTETOSUPPLIER" VARCHAR2(4000), 
	"ISSUE" VARCHAR2(500), 
	"EMAILDATESENTAJC" DATE, 
	"RECORDIDAJC" VARCHAR2(100), 
	"URL_INV" VARCHAR2(1000), 
	"INV_AMOUNT" NUMBER, 
	"SYSTEM_CREATED_AT" TIMESTAMP (6), 
	"BC_SYSTEMID" VARCHAR2(200), 
	"RECORD_TYPE" VARCHAR2(20), 
	"ACCOUNT_NUM" VARCHAR2(50), 
	"LINE_AMOUNT" NUMBER, 
	"REMAINING_AMOUNT" NUMBER, 
	 CONSTRAINT "PK_AJC_BC_INVOICES" UNIQUE ("DOCUMENT_NO", "VENDOR_INV_NUMBER", "VENDOR_NUMBER", "COMPANY_CODE", "INV_DATE", "DUE_DATE", "AMOUNT", "AJC_ATTRIBUTE1", "BC_SYSTEMID", "LINE_AMOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ATISPROD_DATA" 

  CREATE INDEX "AJC"."IDX_AJC_INV_KEY" ON "AJC"."AJC_BC_INVOICES" ("DOCUMENT_NO", "BC_SYSTEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ATISPROD_INDEX" 

  CREATE INDEX "AJC"."AJC_BC_INVOICES_IDX1" ON "AJC"."AJC_BC_INVOICES" ("AJC_ATTRIBUTE1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE UNIQUE INDEX "AJC"."PK_AJC_BC_INVOICES" ON "AJC"."AJC_BC_INVOICES" ("DOCUMENT_NO", "VENDOR_INV_NUMBER", "VENDOR_NUMBER", "COMPANY_CODE", "INV_DATE", "DUE_DATE", "AMOUNT", "AJC_ATTRIBUTE1", "BC_SYSTEMID", "LINE_AMOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
