
  CREATE TABLE "AJC"."AJC_BC_VENDOR_BANKS" 
   (	"SYSTEMID" VARCHAR2(100), 
	"VENDORNO" VARCHAR2(30), 
	"VENDOR_ID" NUMBER, 
	"LEGACYVENDORSITENAME" VARCHAR2(30), 
	"VENDOR_SITE_ID" NUMBER, 
	"BANKCODE" VARCHAR2(240), 
	"NAME" VARCHAR2(200), 
	"NAME2" VARCHAR2(200), 
	"ADDRESS" VARCHAR2(200), 
	"ADDRESS2" VARCHAR2(200), 
	"CITY" VARCHAR2(200), 
	"STATE" VARCHAR2(200), 
	"ZIPCODE" VARCHAR2(200), 
	"COUNTRYREGIONCODE" VARCHAR2(200), 
	"PHONENO" VARCHAR2(200), 
	"CONTACT" VARCHAR2(200), 
	"CURRENCYCODE" VARCHAR2(200), 
	"BANKBRANCHO" VARCHAR2(200), 
	"BANKACCOUNTNO" VARCHAR2(200), 
	"TRANSITNO" VARCHAR2(200), 
	"BANKTYPECODE" VARCHAR2(200), 
	"EMAIL" VARCHAR2(200), 
	"HOMEPAGE" VARCHAR2(200), 
	"BANKCLEARINGSTANDARD" VARCHAR2(200), 
	"BANKCLEARINGCODE" VARCHAR2(200), 
	"USEFORELECTRONICPAYMENTS" VARCHAR2(200), 
	"FAXNO" VARCHAR2(200), 
	"SWIFTCODE" VARCHAR2(200), 
	"IBAN" VARCHAR2(200), 
	"SYSTEMMODIFIEDBY" VARCHAR2(200), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"PROCESSED_DATE" DATE, 
	"STATUS" VARCHAR2(30), 
	"MESSAGE" VARCHAR2(1000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_V_BANKS_BNAME_I2" ON "AJC"."AJC_BC_VENDOR_BANKS" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_V_BANKS_RID_I3" ON "AJC"."AJC_BC_VENDOR_BANKS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_V_BANKS_STATUS_I4" ON "AJC"."AJC_BC_VENDOR_BANKS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_V_BANKS_STATUS_I5" ON "AJC"."AJC_BC_VENDOR_BANKS" ("PROCESSED_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_V_BANKS_STATUS_I6" ON "AJC"."AJC_BC_VENDOR_BANKS" ("SYSTEMMODIFIEDBY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_V_BANKS_STATUS_I7" ON "AJC"."AJC_BC_VENDOR_BANKS" ("SYSTEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_V_BANKS_VNUM_I1" ON "AJC"."AJC_BC_VENDOR_BANKS" ("VENDORNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_VENDOR_BANKS" FOR "AJC"."AJC_BC_VENDOR_BANKS"
