
  CREATE TABLE "AJC"."AJC_BC_CUST_CONTACT_COMM" 
   (	"CUSTOMER_ID" NUMBER, 
	"ADDRESS_ID" NUMBER, 
	"CONTACT_NUMBER" VARCHAR2(30), 
	"LAST_NAME" VARCHAR2(50), 
	"FIRST_NAME" VARCHAR2(40), 
	"TITLE" VARCHAR2(30), 
	"JOB_TITLE" VARCHAR2(100), 
	"CONTACT_POINT_TYPE" VARCHAR2(30), 
	"AREA_CODE" VARCHAR2(10), 
	"PHONE_NUMBER" VARCHAR2(50), 
	"EXTENSION" VARCHAR2(20), 
	"EMAIL_ADDRESS" VARCHAR2(2000), 
	"PRIMARY_FLAG" VARCHAR2(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_CUST_CONTACT_COMM" FOR "AJC"."AJC_BC_CUST_CONTACT_COMM"
