
  CREATE TABLE "AJC"."AJC_BC_COMPANIES" 
   (	"BC_COMPANY_NAME" VARCHAR2(100), 
	"ORACLE_COMPANY_NUMBER" VARCHAR2(2), 
	"LEGAL_ENTITY_NAME" VARCHAR2(100), 
	"STATUS" VARCHAR2(20), 
	"CURRENCY" VARCHAR2(15), 
	"COUNTRY" VARCHAR2(30), 
	"ROLLS_UP_TO" VARCHAR2(30), 
	"ORG_NAME" VARCHAR2(240), 
	"ORG_ID" NUMBER, 
	"SET_OF_BOOKS_NAME" VARCHAR2(240), 
	"SET_OF_BOOKS_ID" NUMBER, 
	"BC_COMPANY_ID" VARCHAR2(100), 
	"AR_RESP_ID" NUMBER, 
	"AP_RESP_ID" NUMBER, 
	"ALLOW_ORDERS" VARCHAR2(1), 
	"SEND_VENDORS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_COMPANIES_IDX1" ON "AJC"."AJC_BC_COMPANIES" ("ORG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_COMPANIES_IDX2" ON "AJC"."AJC_BC_COMPANIES" ("ORACLE_COMPANY_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_COMPANIES" FOR "AJC"."AJC_BC_COMPANIES"
