
  CREATE TABLE "AJC"."AJC_BC_LOGS" 
   (	"IFC" VARCHAR2(100), 
	"SEQ" NUMBER, 
	"TEXT" VARCHAR2(2000), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_LOGS_I1" ON "AJC"."AJC_BC_LOGS" ("IFC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  ALTER INDEX "AJC"."AJC_BC_LOGS_I1"  UNUSABLE

  CREATE INDEX "AJC"."AJC_BC_LOGS_I2" ON "AJC"."AJC_BC_LOGS" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  ALTER INDEX "AJC"."AJC_BC_LOGS_I2"  UNUSABLE

  CREATE INDEX "AJC"."AJC_BC_LOGS_I3" ON "AJC"."AJC_BC_LOGS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  ALTER INDEX "AJC"."AJC_BC_LOGS_I3"  UNUSABLE

  CREATE INDEX "AJC"."AJC_BC_LOGS_I5" ON "AJC"."AJC_BC_LOGS" ("REQUEST_ID", "IFC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  ALTER INDEX "AJC"."AJC_BC_LOGS_I5"  UNUSABLE

  CREATE INDEX "AJC"."AJC_BC_LOGS_I4" ON "AJC"."AJC_BC_LOGS" (TRUNC("CREATION_DATE")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  ALTER INDEX "AJC"."AJC_BC_LOGS_I4"  UNUSABLE

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_LOGS" FOR "AJC"."AJC_BC_LOGS"
