
  CREATE TABLE "AJC"."AJC_BC_PAYMENT_TERMS" 
   (	"CODE" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(200), 
	"CALCPMTDISCONCRMEMOS" VARCHAR2(20), 
	"COUPLEDTOCRM" VARCHAR2(20), 
	"DISCOUNT" VARCHAR2(20), 
	"DISCOUNTDATECALCULATION" VARCHAR2(20), 
	"DUEDATECALCULATION" VARCHAR2(20), 
	"SATPAYMENTTERM" VARCHAR2(100), 
	"ID" VARCHAR2(100), 
	"LASTMODIFIEDDATETIME" VARCHAR2(100), 
	"ACCOUNTSTATEMENTDUEDAYS" VARCHAR2(100), 
	"TYPE" VARCHAR2(100), 
	"INACTIVE" VARCHAR2(1), 
	"SYSTEMMODIFIEDBY" VARCHAR2(200), 
	"NAME" VARCHAR2(50), 
	"MODULE" VARCHAR2(2), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"PROCESSED_DATE" DATE, 
	"STATUS" VARCHAR2(30), 
	"MESSAGE" VARCHAR2(1000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_PT_CODE_I1" ON "AJC"."AJC_BC_PAYMENT_TERMS" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_PT_CODE_I3" ON "AJC"."AJC_BC_PAYMENT_TERMS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_PT_CODE_I2" ON "AJC"."AJC_BC_PAYMENT_TERMS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_PT_CODE_I4" ON "AJC"."AJC_BC_PAYMENT_TERMS" ("SYSTEMMODIFIEDBY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_PAYMENT_TERMS" FOR "AJC"."AJC_BC_PAYMENT_TERMS"
