
  CREATE TABLE "AJC"."AJC_BC_GL_ENTRY" 
   (	"DOCUMENT_NO" VARCHAR2(500) NOT NULL ENABLE, 
	"ENTRY_NO" NUMBER NOT NULL ENABLE, 
	"SOURCE_CODE" VARCHAR2(500), 
	"COMPANY_CODE" NUMBER, 
	"POSTING_DATE" DATE, 
	"AMOUNT" NUMBER, 
	"ACCOUNT_NUMBER" NUMBER, 
	"WORKSHEET_CODE" NUMBER, 
	"CATEGORY" VARCHAR2(300), 
	"SYNC_COMPANY_ID" VARCHAR2(500), 
	"SYNC_DATE" DATE, 
	"CREATION_DATE" DATE, 
	"GENPOSTINGTYPE" VARCHAR2(1000), 
	 CONSTRAINT "PK_AJC_BC_GL_ENTRY" UNIQUE ("DOCUMENT_NO", "ENTRY_NO", "SYNC_COMPANY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ATISPROD_DATA" 

  CREATE UNIQUE INDEX "AJC"."PK_AJC_BC_GL_ENTRY" ON "AJC"."AJC_BC_GL_ENTRY" ("DOCUMENT_NO", "ENTRY_NO", "SYNC_COMPANY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
