
  CREATE TABLE "AJC"."AJC_BC_GL_BALANCES_YTD" 
   (	"ORACLE_COMPANY" VARCHAR2(25), 
	"ORACLE_ACCOUNT" VARCHAR2(25), 
	"ORACLE_DEPT" VARCHAR2(25), 
	"ORACLE_PRODUCT" VARCHAR2(25), 
	"ORACLE_DEST" VARCHAR2(25), 
	"ORACLE_ORIGIN" VARCHAR2(25), 
	"ORACLE_INTERCOMPANY" VARCHAR2(25), 
	"BC_COMPANY" VARCHAR2(100), 
	"BC_ACCOUNT" VARCHAR2(100), 
	"BC_DEPT" VARCHAR2(100), 
	"BC_PRODUCT" VARCHAR2(100), 
	"BC_DEST" VARCHAR2(100), 
	"BC_OFFICE" VARCHAR2(100), 
	"BC_ORIGIN" VARCHAR2(100), 
	"BC_INTERCOMPANY" VARCHAR2(100), 
	"BEGINNING_BALANCE" NUMBER, 
	"DEBITS" NUMBER, 
	"CREDITS" NUMBER, 
	"ENDING_BALANCE" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"PERIOD_YEAR" NUMBER, 
	"CURRENCY_CODE" VARCHAR2(15), 
	"TRANSLATED_ENDING_BALANCE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_GL_BALANCES_YTD" FOR "AJC"."AJC_BC_GL_BALANCES_YTD"
