
  CREATE TABLE "AJC"."AJC_BC_INC_AP_CERTIFY_INVOICES" 
   (	"INVOICE_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"INVOICE_NUM" VARCHAR2(50), 
	"INVOICE_TYPE_LOOKUP_CODE" VARCHAR2(25), 
	"INVOICE_DATE" DATE, 
	"PO_NUMBER" VARCHAR2(20), 
	"VENDOR_ID" NUMBER(15,0), 
	"VENDOR_NUM" VARCHAR2(30), 
	"VENDOR_NAME" VARCHAR2(240), 
	"VENDOR_SITE_ID" NUMBER(15,0), 
	"VENDOR_SITE_CODE" VARCHAR2(15), 
	"INVOICE_AMOUNT" NUMBER, 
	"INVOICE_CURRENCY_CODE" VARCHAR2(15), 
	"EXCHANGE_RATE" NUMBER, 
	"EXCHANGE_RATE_TYPE" VARCHAR2(30), 
	"EXCHANGE_DATE" DATE, 
	"TERMS_ID" NUMBER(15,0), 
	"TERMS_NAME" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(240), 
	"AWT_GROUP_ID" NUMBER(15,0), 
	"AWT_GROUP_NAME" VARCHAR2(25), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE1" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE2" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE3" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE4" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE5" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE6" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE7" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE8" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE9" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE10" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE11" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE12" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE13" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE14" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE15" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE16" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE17" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE18" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE19" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE20" VARCHAR2(150), 
	"SOURCE" VARCHAR2(80), 
	"GROUP_ID" VARCHAR2(80), 
	"DOC_CATEGORY_CODE" VARCHAR2(30), 
	"VOUCHER_NUM" VARCHAR2(50), 
	"PAYMENT_METHOD_LOOKUP_CODE" VARCHAR2(25), 
	"PAY_GROUP_LOOKUP_CODE" VARCHAR2(25), 
	"GOODS_RECEIVED_DATE" DATE, 
	"INVOICE_RECEIVED_DATE" DATE, 
	"WORKFLOW_FLAG" VARCHAR2(1), 
	"GL_DATE" DATE, 
	"ACCTS_PAY_CODE_COMBINATION_ID" NUMBER(15,0), 
	"USSGL_TRANSACTION_CODE" VARCHAR2(30), 
	"EXCLUSIVE_PAYMENT_FLAG" VARCHAR2(1), 
	"ORG_ID" NUMBER(15,0), 
	"AMOUNT_APPLICABLE_TO_DISCOUNT" NUMBER, 
	"PAYMENT_CROSS_RATE_TYPE" VARCHAR2(30), 
	"PAYMENT_CROSS_RATE_DATE" DATE, 
	"PAYMENT_CROSS_RATE" NUMBER, 
	"PAYMENT_CURRENCY_CODE" VARCHAR2(15), 
	"PREPAY_NUM" VARCHAR2(50), 
	"PREPAY_DIST_NUM" NUMBER(15,0), 
	"PREPAY_APPLY_AMOUNT" NUMBER, 
	"PREPAY_GL_DATE" DATE, 
	"INVOICE_INCLUDES_PREPAY_FLAG" VARCHAR2(1), 
	"NO_XRATE_BASE_AMOUNT" NUMBER, 
	"VENDOR_EMAIL_ADDRESS" VARCHAR2(2000), 
	"TERMS_DATE" DATE, 
	"REQUESTER_ID" NUMBER(10,0), 
	"SHIP_TO_LOCATION" VARCHAR2(40), 
	"EXTERNAL_DOC_REF" VARCHAR2(240), 
	"ACCTS_PAY_CODE_CONCATENATED" VARCHAR2(250), 
	"SET_OF_BOOKS_ID" VARCHAR2(10), 
	"SET_OF_BOOKS_NAME" VARCHAR2(240), 
	"DIST_CODE_COMBINATION" VARCHAR2(10), 
	"COMPANY" VARCHAR2(10), 
	"ACCOUNT" VARCHAR2(20), 
	"ACCOUNT_DESCRIPTION" VARCHAR2(240), 
	"DEPARTMENT" VARCHAR2(10), 
	"PRODUCT" VARCHAR2(10), 
	"DESTINATION" VARCHAR2(10), 
	"OFFICE" VARCHAR2(10), 
	"ORIGIN" VARCHAR2(10), 
	"INTERCOMPANY" VARCHAR2(10), 
	"JSON_DATA" CLOB, 
	"JSON_DATA_RESPONSE" CLOB, 
	"STATUS" VARCHAR2(25), 
	"ERROR_MESSAGE" VARCHAR2(1000), 
	"REQUEST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("JSON_DATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("JSON_DATA_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  CREATE INDEX "AJC"."AJC_BC_CERTIFY_STATUS_I2" ON "AJC"."AJC_BC_INC_AP_CERTIFY_INVOICES" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CERTIFY_RID_I1" ON "AJC"."AJC_BC_INC_AP_CERTIFY_INVOICES" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CERTIFY_C_I4" ON "AJC"."AJC_BC_INC_AP_CERTIFY_INVOICES" ("COMPANY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CERTIFY_IID_I3" ON "AJC"."AJC_BC_INC_AP_CERTIFY_INVOICES" ("INVOICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_INC_AP_CERTIFY_INVOICES" FOR "AJC"."AJC_BC_INC_AP_CERTIFY_INVOICES"
