
  CREATE TABLE "AJC"."AJC_BC_AR_DAYS_LATE_DT_ZONE_R" 
   (	"COLUMN1" VARCHAR2(100), 
	"COLUMN2" VARCHAR2(100), 
	"COLUMN5" NUMBER, 
	"COLUMN6" NUMBER, 
	"COLUMN7" NUMBER, 
	"COLUMN8" NUMBER, 
	"COLUMN9" NUMBER, 
	"COLUMN10" NUMBER, 
	"COLUMN11" NUMBER, 
	"COLUMN12" NUMBER, 
	"COLUMN13" NUMBER, 
	"COLUMN14" NUMBER, 
	"COLUMN15" NUMBER, 
	"COLUMN16" NUMBER, 
	"COLUMN17" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
