
  CREATE TABLE "AJC"."AJC_BC_AP_INVOICES" 
   (	"INVOICE_NUMBER" VARCHAR2(50 CHAR), 
	"INVOICE_DATE" DATE, 
	"DUE_DATE" DATE, 
	"VENDOR_ID" NUMBER, 
	"VENDOR_NAME" VARCHAR2(240 CHAR), 
	"WORKSHEET_NUMBER" VARCHAR2(240 CHAR), 
	"VENDOR_NUMBER" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
