
  CREATE TABLE "AJC"."AJC_BC_DCLE_CONTROL" 
   (	"SYSTEMID" VARCHAR2(100), 
	"AMOUNT" NUMBER, 
	"AMOUNTLCY" NUMBER, 
	"AMOUNTINCOMPANYCURRENCYINE" NUMBER, 
	"APPLICATIONNO" NUMBER, 
	"APPLIEDCUSTLEDGERENTRYNO" NUMBER, 
	"COMPANYCURRENCYCODEINE" VARCHAR2(15), 
	"CREDITAMOUNT" NUMBER, 
	"CREDITAMOUNTLCY" NUMBER, 
	"CURRENCYCODE" VARCHAR2(15), 
	"CUSTLEDGERENTRYNO" NUMBER, 
	"CUSTOMERNO" VARCHAR2(30), 
	"DEBITAMOUNT" NUMBER, 
	"DEBITAMOUNTLCY" NUMBER, 
	"DOCUMENTNO" VARCHAR2(40), 
	"DOCUMENTTYPE" VARCHAR2(40), 
	"ENTRYNO" NUMBER, 
	"ENTRYTYPE" VARCHAR2(100), 
	"INITIALDOCUMENTTYPE" VARCHAR2(30), 
	"INITIALENTRYDUEDATE" VARCHAR2(10), 
	"INITIALENTRYGLOBALDIM1" VARCHAR2(10), 
	"INITIALENTRYGLOBALDIM2" VARCHAR2(10), 
	"JOURNALBATCHNAME" VARCHAR2(100), 
	"LEDGERENTRYAMOUNT" VARCHAR2(10), 
	"MAXPAYMENTTOLERANCE" NUMBER, 
	"POSTINGDATE" VARCHAR2(10), 
	"REASONCODE" VARCHAR2(100), 
	"REMAININGPMTDISCPOSSIBLE" NUMBER, 
	"SOURCECODE" VARCHAR2(30), 
	"SYSTEMCREATEDAT" VARCHAR2(30), 
	"SYSTEMCREATEDBY" VARCHAR2(50), 
	"SYSTEMMODIFIEDAT" VARCHAR2(30), 
	"SYSTEMMODIFIEDBY" VARCHAR2(50), 
	"TAXJURISDICTIONCODE" VARCHAR2(30), 
	"TRANSACTIONNO" NUMBER, 
	"UNAPPLIED" VARCHAR2(10), 
	"UNAPPLIEDBYENTRYNO" NUMBER, 
	"USETAX" VARCHAR2(10), 
	"USERID" VARCHAR2(50), 
	"CREATEDDATE" VARCHAR2(10), 
	"CREATEDTIME" VARCHAR2(20), 
	"MODIFIEDDATE" VARCHAR2(10), 
	"MODIFIEDTIME" VARCHAR2(20), 
	"STATUS" VARCHAR2(10), 
	"CREATION_DATE" DATE, 
	"REQUEST_ID" NUMBER, 
	"BC_ENVIRONMENT" VARCHAR2(20), 
	"TRX_NUMBER" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_DCLEC_ET_I7" ON "AJC"."AJC_BC_DCLE_CONTROL" ("ENTRYTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_DCLEC_IDT_I8" ON "AJC"."AJC_BC_DCLE_CONTROL" ("INITIALDOCUMENTTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_DCLEC_CLENO_I9" ON "AJC"."AJC_BC_DCLE_CONTROL" ("CUSTLEDGERENTRYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_DCLEC_TRX_I11" ON "AJC"."AJC_BC_DCLE_CONTROL" ("TRX_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_DCLEC_IEGD1_I10" ON "AJC"."AJC_BC_DCLE_CONTROL" ("INITIALENTRYGLOBALDIM1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_DCLEC_RID_I1" ON "AJC"."AJC_BC_DCLE_CONTROL" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_DCLEC_ENO_I2" ON "AJC"."AJC_BC_DCLE_CONTROL" ("ENTRYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_DCLEC_DNO_I3" ON "AJC"."AJC_BC_DCLE_CONTROL" ("DOCUMENTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_DCLEC_ST_I4" ON "AJC"."AJC_BC_DCLE_CONTROL" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_DCLEC_SID_I5" ON "AJC"."AJC_BC_DCLE_CONTROL" ("SYSTEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_DCLEC_ACLENO_I6" ON "AJC"."AJC_BC_DCLE_CONTROL" ("APPLIEDCUSTLEDGERENTRYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_DCLE_CONTROL" FOR "AJC"."AJC_BC_DCLE_CONTROL"
