
  CREATE TABLE "AJC"."AJC_BC_CUSTOMERS_AIG_LIMIT" 
   (	"CUSTOMER_NUMBER" VARCHAR2(20), 
	"ORACLE_AIG_LIMIT" VARCHAR2(150), 
	"BC_AIG_LIMIT" VARCHAR2(150)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE UNIQUE INDEX "AJC"."AJC_BC_CUST_AIG_LIMIT_I1" ON "AJC"."AJC_BC_CUSTOMERS_AIG_LIMIT" ("CUSTOMER_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_CUSTOMERS_AIG_LIMIT" FOR "AJC"."AJC_BC_CUSTOMERS_AIG_LIMIT"
