
  CREATE TABLE "AJC"."AJC_BC_PURGE_TABLES_COLUMNS" 
   (	"COMPANY" VARCHAR2(20) NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"COLUMN_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PURGE_ACTION" VARCHAR2(20) NOT NULL ENABLE, 
	"ENABLED" VARCHAR2(1) NOT NULL ENABLE, 
	"TABLE_SIZE_BEFORE_MB" NUMBER, 
	"TABLE_SIZE_AFTER_MB" NUMBER, 
	"CLOB_SIZE_BEFORE_MB" NUMBER, 
	"CLOB_SIZE_AFTER_MB" NUMBER, 
	"ROWS_TO_UPDATE" NUMBER, 
	"ROWS_UPDATED" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE UNIQUE INDEX "APPS_ORAFSYS"."AJC_BC_PCLOBTC_U1" ON "AJC"."AJC_BC_PURGE_TABLES_COLUMNS" ("COMPANY", "TABLE_NAME", "COLUMN_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_PURGE_TABLES_COLUMNS" FOR "AJC"."AJC_BC_PURGE_TABLES_COLUMNS"
