
  CREATE TABLE "AJC"."AJC_BC_CLE_CONTROL" 
   (	"SYSTEMID" VARCHAR2(100), 
	"ACCEPTEDPAYMENTTOLERANCE" NUMBER, 
	"ACCEPTEDPMTDISCTOLERANCE" VARCHAR2(20), 
	"ADJUSTEDCURRENCYFACTOR" NUMBER, 
	"AMOUNT" NUMBER, 
	"AMOUNTLCY" NUMBER, 
	"AMOUNTINCOMPANYCURRENCYINE" NUMBER, 
	"AMOUNTTOAPPLY" NUMBER, 
	"APPLIESTODOCNO" VARCHAR2(30), 
	"APPLIESTODOCTYPE" VARCHAR2(30), 
	"APPLIESTOEXTDOCNO" VARCHAR2(30), 
	"APPLIESTOID" NUMBER, 
	"APPLYINGENTRY" VARCHAR2(30), 
	"BALACCOUNTNO" VARCHAR2(40), 
	"BALACCOUNTTYPE" VARCHAR2(40), 
	"CALCULATEINTEREST" VARCHAR2(10), 
	"CERTIFICATESERIALNO" VARCHAR2(10), 
	"CLOSEDATDATE" VARCHAR2(10), 
	"CLOSEDBYAMOUNT" NUMBER, 
	"CLOSEDBYAMOUNTLCY" NUMBER, 
	"CLOSEDBYCURRENCYAMOUNT" NUMBER, 
	"CLOSEDBYCURRENCYCODE" VARCHAR2(15), 
	"CLOSEDBYENTRYNO" NUMBER, 
	"CLOSINGINTERESTCALCULATED" VARCHAR2(10), 
	"COMPANYCURRENCYCODEINE" VARCHAR2(15), 
	"COMPANYADJUSTEDCURRFACTORINE" NUMBER, 
	"COMPANYORIGINALCURRFACTORINE" NUMBER, 
	"COSTTYPEDIMENSIONCODEINE" VARCHAR2(20), 
	"CREDITAMOUNT" NUMBER, 
	"CREDITAMOUNTLCY" NUMBER, 
	"CURRENCYCODE" VARCHAR2(15), 
	"CUSTOMERDIMVALUECODEINE" VARCHAR2(15), 
	"CUSTOMERDIMENSIONCODEINE" VARCHAR2(15), 
	"CUSTOMERNAME" VARCHAR2(240), 
	"CUSTOMERNO" VARCHAR2(30), 
	"CUSTOMERPOSTINGGROUP" VARCHAR2(15), 
	"DATETIMECANCELED" VARCHAR2(30), 
	"DATETIMEFIRSTREQSENT" VARCHAR2(30), 
	"DATETIMESENT" VARCHAR2(30), 
	"DATETIMESTAMPED" VARCHAR2(30), 
	"DEBITAMOUNT" NUMBER, 
	"DEBITAMOUNTLCY" NUMBER, 
	"DESCRIPTION" VARCHAR2(240), 
	"DIMENSIONSETID" NUMBER, 
	"DIRECTDEBITMANDATEID" NUMBER, 
	"DOCUMENTDATE" VARCHAR2(10), 
	"DOCUMENTNO" VARCHAR2(40), 
	"DOCUMENTTYPE" VARCHAR2(30), 
	"DUEDATE" VARCHAR2(10), 
	"COMMENTS" VARCHAR2(2000), 
	"EDIOUTBOUNDENTRYEXISTSINE" VARCHAR2(10), 
	"ENTRYNO" NUMBER, 
	"GLOBALDIMENSION1CODE" VARCHAR2(10), 
	"GLOBALDIMENSION2CODE" VARCHAR2(10), 
	"JOURNALBATCHNAME" VARCHAR2(100), 
	"OPEN" VARCHAR2(10), 
	"ORIGINALAMOUNT" NUMBER, 
	"ORIGINALAMTLCY" NUMBER, 
	"ORIGINALCURRENCYFACTOR" NUMBER, 
	"ORIGINALPMTDISCPOSSIBLE" NUMBER, 
	"OVERAPPLICATIONAMOUNTINE" NUMBER, 
	"POSTINGDATE" VARCHAR2(10), 
	"PREPAYMENT" VARCHAR2(10), 
	"REMAININGAMOUNT" NUMBER, 
	"REMAININGAMTLCY" NUMBER, 
	"REVERSED" VARCHAR2(10), 
	"REVERSEDENTRYNO" NUMBER, 
	"REVERSEDBYENTRYNO" NUMBER, 
	"SALESLCY" NUMBER, 
	"SALESPERSONCODE" VARCHAR2(30), 
	"SELECTEDINE" VARCHAR2(10), 
	"SELLTOCUSTOMERNO" VARCHAR2(30), 
	"SHORTCUTDIMENSION3CODE" VARCHAR2(20), 
	"SHORTCUTDIMENSION4CODE" VARCHAR2(20), 
	"SHORTCUTDIMENSION5CODE" VARCHAR2(20), 
	"SHORTCUTDIMENSION6CODE" VARCHAR2(20), 
	"SHORTCUTDIMENSION7CODE" VARCHAR2(20), 
	"SHORTCUTDIMENSION8CODE" VARCHAR2(20), 
	"SOURCECODE" VARCHAR2(20), 
	"CREDITMEMOADJUSTMENT" VARCHAR2(10), 
	"PAYMENTTERMSCODE" VARCHAR2(30), 
	"SYSTEMCREATEDAT" VARCHAR2(30), 
	"SYSTEMCREATEDBY" VARCHAR2(50), 
	"SYSTEMMODIFIEDAT" VARCHAR2(30), 
	"SYSTEMMODIFIEDBY" VARCHAR2(50), 
	"TRANSACTIONNO" NUMBER, 
	"USERID" VARCHAR2(50), 
	"CREATEDDATE" VARCHAR2(10), 
	"CREATEDTIME" VARCHAR2(20), 
	"MODIFIEDDATE" VARCHAR2(10), 
	"MODIFIEDTIME" VARCHAR2(20), 
	"STATUS" VARCHAR2(10), 
	"CREATION_DATE" DATE, 
	"REQUEST_ID" NUMBER, 
	"BC_ENVIRONMENT" VARCHAR2(20), 
	"TRX_NUMBER" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_BCE_I10" ON "AJC"."AJC_BC_CLE_CONTROL" ("BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_TRX_I12" ON "AJC"."AJC_BC_CLE_CONTROL" ("TRX_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_CN_I11" ON "AJC"."AJC_BC_CLE_CONTROL" ("CUSTOMERNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_RID_I1" ON "AJC"."AJC_BC_CLE_CONTROL" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_DNO_I2" ON "AJC"."AJC_BC_CLE_CONTROL" ("DOCUMENTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_CBENO_I3" ON "AJC"."AJC_BC_CLE_CONTROL" ("CLOSEDBYENTRYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_ST_I4" ON "AJC"."AJC_BC_CLE_CONTROL" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_SID_I5" ON "AJC"."AJC_BC_CLE_CONTROL" ("SYSTEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_BAT_I6" ON "AJC"."AJC_BC_CLE_CONTROL" ("BALACCOUNTTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_ENO_I7" ON "AJC"."AJC_BC_CLE_CONTROL" ("ENTRYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_GD1C_I9" ON "AJC"."AJC_BC_CLE_CONTROL" ("GLOBALDIMENSION1CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_CLEC_DT_I8" ON "AJC"."AJC_BC_CLE_CONTROL" ("DOCUMENTTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_CLE_CONTROL" FOR "AJC"."AJC_BC_CLE_CONTROL"
