
  CREATE TABLE "AJC"."AJC_BC_GLE_CONTROL" 
   (	"SYSTEMID" VARCHAR2(100), 
	"ACCOUNTID" VARCHAR2(100), 
	"ADDCURRENCYCREDITAMOUNT" NUMBER, 
	"ADDCURRENCYDEBITAMOUNT" NUMBER, 
	"ADDITIONALCURRENCYAMOUNT" NUMBER, 
	"AMOUNT" NUMBER, 
	"BALACCOUNTNO" VARCHAR2(40), 
	"BALACCOUNTTYPE" VARCHAR2(40), 
	"BUSINESSUNITCODE" VARCHAR2(40), 
	"COMMENTS" VARCHAR2(1000), 
	"COSTALLOCATIONSTATUSINE" VARCHAR2(20), 
	"COSTTYPEDIMENSIONCODEINE" VARCHAR2(20), 
	"CREDITAMOUNT" NUMBER, 
	"DEBITAMOUNT" NUMBER, 
	"DESCRIPTION" VARCHAR2(240), 
	"DIMENSIONSETID" NUMBER, 
	"DOCUMENTDATE" VARCHAR2(10), 
	"DOCUMENTNO" VARCHAR2(40), 
	"DOCUMENTTYPE" VARCHAR2(30), 
	"ENTRYNO" NUMBER, 
	"EXPENSETYPEINE" VARCHAR2(30), 
	"EXTERNALDOCUMENTNO" VARCHAR2(35), 
	"FAENTRYNO" NUMBER, 
	"FAENTRYTYPE" VARCHAR2(30), 
	"GLACCOUNTNAME" VARCHAR2(100), 
	"GLACCOUNTNO" VARCHAR2(30), 
	"GLOBALDIMENSION1CODE" VARCHAR2(10), 
	"GLOBALDIMENSION2CODE" VARCHAR2(10), 
	"INCOMEBALANCEINE" VARCHAR2(30), 
	"POSTINGDATE" VARCHAR2(10), 
	"PRIORYEARENTRY" VARCHAR2(10), 
	"QUANTITY" NUMBER, 
	"REASONCODE" VARCHAR2(100), 
	"REVERSED" VARCHAR2(10), 
	"REVERSEDENTRYNO" NUMBER, 
	"REVERSEDBYENTRYNO" NUMBER, 
	"SHORTCUTDIMENSION3CODE" VARCHAR2(20), 
	"SHORTCUTDIMENSION4CODE" VARCHAR2(20), 
	"SHORTCUTDIMENSION5CODE" VARCHAR2(20), 
	"SHORTCUTDIMENSION6CODE" VARCHAR2(20), 
	"SHORTCUTDIMENSION7CODE" VARCHAR2(20), 
	"SHORTCUTDIMENSION8CODE" VARCHAR2(20), 
	"SOURCECODE" VARCHAR2(30), 
	"SOURCENO" VARCHAR2(30), 
	"SOURCETYPE" VARCHAR2(30), 
	"SYSTEMCREATEDENTRY" VARCHAR2(10), 
	"SYSTEMCREATEDAT" VARCHAR2(30), 
	"SYSTEMCREATEDBY" VARCHAR2(50), 
	"SYSTEMMODIFIEDAT" VARCHAR2(30), 
	"SYSTEMMODIFIEDBY" VARCHAR2(50), 
	"TRANSACTIONNO" NUMBER, 
	"USETAX" VARCHAR2(10), 
	"USERID" VARCHAR2(50), 
	"VATAMOUNT" NUMBER, 
	"CREATEDDATE" VARCHAR2(10), 
	"CREATEDTIME" VARCHAR2(20), 
	"MODIFIEDDATE" VARCHAR2(10), 
	"MODIFIEDTIME" VARCHAR2(20), 
	"STATUS" VARCHAR2(10), 
	"CREATION_DATE" DATE, 
	"REQUEST_ID" NUMBER, 
	"BC_ENVIRONMENT" VARCHAR2(20), 
	"TRX_NUMBER" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_GLEC_SID_I5" ON "AJC"."AJC_BC_GLE_CONTROL" ("SYSTEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_GLEC_RID_I1" ON "AJC"."AJC_BC_GLE_CONTROL" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_GLEC_ENO_I2" ON "AJC"."AJC_BC_GLE_CONTROL" ("ENTRYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_GLEC_TRX_I8" ON "AJC"."AJC_BC_GLE_CONTROL" ("TRX_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_GLEC_GD1C_I6" ON "AJC"."AJC_BC_GLE_CONTROL" ("GLOBALDIMENSION1CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_GLEC_BCE_I7" ON "AJC"."AJC_BC_GLE_CONTROL" ("BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_GLEC_DNO_I3" ON "AJC"."AJC_BC_GLE_CONTROL" ("DOCUMENTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_GLEC_ST_I4" ON "AJC"."AJC_BC_GLE_CONTROL" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_GLE_CONTROL" FOR "AJC"."AJC_BC_GLE_CONTROL"
