
  CREATE TABLE "AJC"."AJC_BC_TRANSACTIONS" 
   (	"COMPANY" VARCHAR2(50), 
	"ORG_ID" NUMBER, 
	"TRX_NUMBER" VARCHAR2(100), 
	"CUSTOMER_TRX_ID" NUMBER, 
	"CUSTOMER_NAME" VARCHAR2(50), 
	"CUSTOMER_NUMBER" VARCHAR2(30), 
	"CUSTOMER_ID" NUMBER, 
	"TRX_DATE" DATE, 
	"DUE_DATE" DATE, 
	"GL_DATE" DATE, 
	"CURRENCY_CODE" VARCHAR2(15), 
	"AMOUNT" NUMBER, 
	"EXCHANGE_RATE" NUMBER, 
	"PAYMENT_TERMS" VARCHAR2(100), 
	"TERM_ID" NUMBER, 
	"ADDRESS1" VARCHAR2(200), 
	"ADDRESS2" VARCHAR2(200), 
	"STATUS" VARCHAR2(10), 
	"MESSAGE" VARCHAR2(1000), 
	"PROCESSED_DATE" DATE, 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_TRX_REQUEST_ID_I4" ON "AJC"."AJC_BC_TRANSACTIONS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_TRX_STATUS_I3" ON "AJC"."AJC_BC_TRANSACTIONS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_TRX_TRX_NUMBER_I1" ON "AJC"."AJC_BC_TRANSACTIONS" ("TRX_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_TRANSACTIONS" FOR "AJC"."AJC_BC_TRANSACTIONS"
