
  CREATE TABLE "AJC"."AJC_BC_VENDOR_SITE_CONTACTS" 
   (	"COMPANY" VARCHAR2(50), 
	"ORG_ID" NUMBER, 
	"VENDOR_SITE_CODE" VARCHAR2(15), 
	"VENDOR_SITE_ID" NUMBER, 
	"VENDOR_NAME" VARCHAR2(100), 
	"VENDOR_ID" NUMBER, 
	"FIRST" VARCHAR2(15), 
	"LAST" VARCHAR2(20), 
	"PHONE" VARCHAR2(15), 
	"EMAIL" VARCHAR2(2000), 
	"URL" VARCHAR2(2000), 
	"STATUS" VARCHAR2(10), 
	"MESSAGE" VARCHAR2(1000), 
	"PROCESSED_DATE" DATE, 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CONTACT_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_VCONT_LAST_I3" ON "AJC"."AJC_BC_VENDOR_SITE_CONTACTS" ("LAST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_VCONT_FIRST_I3" ON "AJC"."AJC_BC_VENDOR_SITE_CONTACTS" ("FIRST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_VCONT_VSC_I2" ON "AJC"."AJC_BC_VENDOR_SITE_CONTACTS" ("VENDOR_SITE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_VCONT_NAME_I1" ON "AJC"."AJC_BC_VENDOR_SITE_CONTACTS" ("VENDOR_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_VENDOR_SITE_CONTACTS" FOR "AJC"."AJC_BC_VENDOR_SITE_CONTACTS"
