
  CREATE TABLE "AJC"."AJC_BC_ABBYY_INV_LINES_INT" 
   (	"ORG_ID" NUMBER, 
	"VENDOR_ID" NUMBER, 
	"VENDOR_SITE_CODE" VARCHAR2(15), 
	"INVOICE_TYPE_LOOKUP_CODE" VARCHAR2(25), 
	"INVOICE_NUM" VARCHAR2(50), 
	"WORKSHEET_NUMBER" VARCHAR2(240), 
	"ACCRUAL_FUNC_AMOUNT" NUMBER, 
	"ACCRUAL_AMOUNT" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LINE_AMOUNT" NUMBER, 
	"SOURCE_TYPE" VARCHAR2(100), 
	"LINE_NUMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_ABBYY_INV_LINES_INT" FOR "AJC"."AJC_BC_ABBYY_INV_LINES_INT"
