
  CREATE TABLE "AJC"."AJC_BC_ARXAGE_TEMP" 
   (	"TRX_NUMBER" VARCHAR2(30), 
	"TRX_TYPE" VARCHAR2(20), 
	"TERM_ID" NUMBER, 
	"DUE_DATE" DATE, 
	"OUTSTANDING_AMT" NUMBER, 
	"CURRENT_AMT" NUMBER, 
	"CUSTOMER_ID" VARCHAR2(30), 
	"CUSTOMER_SITE_ID" NUMBER, 
	"PAST_DUE_1_30_AMT" NUMBER, 
	"PAST_DUE_31_60_AMT" NUMBER, 
	"OVER_60DAYS_AMT" NUMBER, 
	"AS_OF_DATE" DATE, 
	"ORG_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"RECORD_ID" NUMBER, 
	"TRX_CLASS" VARCHAR2(10), 
	"AJC_TERM_TYPE" VARCHAR2(20), 
	"AJC_COUNTRY_CODE" VARCHAR2(10), 
	"DATA_REC" VARCHAR2(240), 
	"TRANS_OUTSTANDING_AMT" NUMBER, 
	"TRANS_CURRENT_AMT" NUMBER, 
	"TRANS_PAST_DUE_1_30_AMT" NUMBER, 
	"TRANS_PAST_DUE_31_60_AMT" NUMBER, 
	"TRANS_OVER_60DAYS_AMT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_ARXAGE_TEMP" FOR "AJC"."AJC_BC_ARXAGE_TEMP"
