
  CREATE TABLE "AJC"."AJC_BC_AP_HEADERS" 
   (	"INVOICE_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"INVOICE_NUM" VARCHAR2(50), 
	"INVOICE_TYPE_LOOKUP_CODE" VARCHAR2(25), 
	"INVOICE_DATE" DATE, 
	"VENDOR_ID" NUMBER(15,0), 
	"VENDOR_NUM" VARCHAR2(30), 
	"VENDOR_NAME" VARCHAR2(240), 
	"VENDOR_SITE_ID" NUMBER(15,0), 
	"VENDOR_SITE_CODE" VARCHAR2(15), 
	"INVOICE_AMOUNT" NUMBER, 
	"INVOICE_CURRENCY_CODE" VARCHAR2(15), 
	"EXCHANGE_RATE" NUMBER, 
	"EXCHANGE_RATE_TYPE" VARCHAR2(30), 
	"EXCHANGE_DATE" DATE, 
	"TERMS_ID" NUMBER(15,0), 
	"TERMS_NAME" VARCHAR2(50), 
	"TERMS_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(240), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"SOURCE" VARCHAR2(80), 
	"PAYMENT_METHOD_LOOKUP_CODE" VARCHAR2(25), 
	"PAY_GROUP_LOOKUP_CODE" VARCHAR2(25), 
	"GL_DATE" DATE, 
	"ORG_ID" NUMBER(15,0), 
	"SET_OF_BOOKS_ID" VARCHAR2(10), 
	"SET_OF_BOOKS_NAME" VARCHAR2(240), 
	"COMPANY" VARCHAR2(10), 
	"ACCOUNT" VARCHAR2(20), 
	"ACCOUNT_DESCRIPTION" VARCHAR2(240), 
	"DEPARTMENT" VARCHAR2(10), 
	"PRODUCT" VARCHAR2(10), 
	"DESTINATION" VARCHAR2(10), 
	"OFFICE" VARCHAR2(10), 
	"ORIGIN" VARCHAR2(10), 
	"INTERCOMPANY" VARCHAR2(10), 
	"JSON_DATA" CLOB, 
	"JSON_DATA_RESPONSE" CLOB, 
	"STATUS" VARCHAR2(25), 
	"ERROR_MESSAGE" VARCHAR2(1000), 
	"REQUEST_ID" NUMBER, 
	"TYPE" VARCHAR2(20), 
	"PDF_FILE_URL" VARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("JSON_DATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("JSON_DATA_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  CREATE INDEX "AJC"."AJC_BC_AP_RID_I1" ON "AJC"."AJC_BC_AP_HEADERS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_AP_STATUS_I2" ON "AJC"."AJC_BC_AP_HEADERS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_AP_IID_I3" ON "AJC"."AJC_BC_AP_HEADERS" ("INVOICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_AP_IC_I4" ON "AJC"."AJC_BC_AP_HEADERS" ("COMPANY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_AP_ERR_I5" ON "AJC"."AJC_BC_AP_HEADERS" ("ERROR_MESSAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_AP_HEADERS" FOR "AJC"."AJC_BC_AP_HEADERS"
