
  CREATE TABLE "AJC"."AJC_BC_ACCOUNT_DIMENSIONS" 
   (	"GL_ACCOUNT" VARCHAR2(100), 
	"DIMENSION_CODE" VARCHAR2(100), 
	"DIMENSION_VALUE_CODE" VARCHAR2(100), 
	"VALUE_POSTING" VARCHAR2(100), 
	"ALLOWED_VALUES_FILTERS" VARCHAR2(100), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_AD_DC_I2" ON "AJC"."AJC_BC_ACCOUNT_DIMENSIONS" ("DIMENSION_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_AD_ACCOUNT_I1" ON "AJC"."AJC_BC_ACCOUNT_DIMENSIONS" ("GL_ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_ACCOUNT_DIMENSIONS" FOR "AJC"."AJC_BC_ACCOUNT_DIMENSIONS"
