
  CREATE TABLE "AJC"."AJC_BC_ABBYY_INVOICES_INT" 
   (	"ORG_ID" NUMBER NOT NULL ENABLE, 
	"VENDOR_ID" NUMBER NOT NULL ENABLE, 
	"VENDOR_SITE_CODE" VARCHAR2(15), 
	"ADDRESS_LINE1" VARCHAR2(240), 
	"ADDRESS_LINE2" VARCHAR2(240), 
	"ADDRESS_LINE3" VARCHAR2(240), 
	"CITY" VARCHAR2(60), 
	"STATE" VARCHAR2(50), 
	"ZIP" VARCHAR2(20), 
	"PROVINCE" VARCHAR2(150), 
	"COUNTRY" VARCHAR2(25), 
	"INVOICE_NUM" VARCHAR2(50) NOT NULL ENABLE, 
	"INVOICE_DATE" DATE NOT NULL ENABLE, 
	"INVOICE_TYPE_LOOKUP_CODE" VARCHAR2(25) NOT NULL ENABLE, 
	"INVOICE_AMOUNT" NUMBER NOT NULL ENABLE, 
	"INVOICE_CURRENCY_CODE" VARCHAR2(15), 
	"DESCRIPTION" VARCHAR2(240), 
	"WORKSHEET_NUMBER" VARCHAR2(240), 
	"STATUS_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(2000), 
	"CREATED_BY" NUMBER NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" NUMBER NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"ABBYY_USER_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"FILE_PATH" VARCHAR2(2000) NOT NULL ENABLE, 
	"INVOICE_ID" NUMBER, 
	"VENDOR_NAME" VARCHAR2(240), 
	"VENDOR_NUM" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE UNIQUE INDEX "AJC"."AJC_BC_ABBYY_INVOICES_INT_U1" ON "AJC"."AJC_BC_ABBYY_INVOICES_INT" ("VENDOR_ID", "INVOICE_NUM", "ORG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_ABBYY_INVOICES_INT" FOR "AJC"."AJC_BC_ABBYY_INVOICES_INT"
