
  CREATE TABLE "AJC"."AJC_BC_ATIS_GL_LINES" 
   (	"JE_HEADER_ID" NUMBER NOT NULL ENABLE, 
	"JE_LINE_NUM" NUMBER NOT NULL ENABLE, 
	"BC_ACCOUNT" VARCHAR2(100), 
	"REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"DOCUMENTNO" VARCHAR2(20), 
	"STATUS" VARCHAR2(20), 
	"ERROR_MESSAGE" VARCHAR2(2000), 
	"COMPANY" VARCHAR2(100), 
	"DEPARTMENT" VARCHAR2(100), 
	"PRODUCT" VARCHAR2(100), 
	"DESTINATION" VARCHAR2(100), 
	"OFFICE" VARCHAR2(100), 
	"ORIGIN" VARCHAR2(100), 
	"DIVISION" VARCHAR2(100), 
	"WORKSHEET" VARCHAR2(100), 
	"JSON_NUMBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_ATIS_GL_LINES_N3" ON "AJC"."AJC_BC_ATIS_GL_LINES" ("DOCUMENTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_ATIS_GL_LINES_N4" ON "AJC"."AJC_BC_ATIS_GL_LINES" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_ATIS_GL_LINES_N1" ON "AJC"."AJC_BC_ATIS_GL_LINES" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_ATIS_GL_LINES_N2" ON "AJC"."AJC_BC_ATIS_GL_LINES" ("REQUEST_ID", "JE_HEADER_ID", "JE_LINE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_ATIS_GL_LINES" FOR "AJC"."AJC_BC_ATIS_GL_LINES"
