
  CREATE TABLE "AJC"."AJC_BC_GL_MAPPING" 
   (	"ORACLE_SEGMENT" VARCHAR2(20), 
	"ORACLE_VALUE" VARCHAR2(20), 
	"BC_DIMENSION" VARCHAR2(20), 
	"BC_VALUE" VARCHAR2(20), 
	"ACTIVE" VARCHAR2(1), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_GL_MAPPING_N1" ON "AJC"."AJC_BC_GL_MAPPING" ("ORACLE_SEGMENT", "ORACLE_VALUE", "BC_DIMENSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE UNIQUE INDEX "AJC"."AJC_BC_GL_MAPPING_U1" ON "AJC"."AJC_BC_GL_MAPPING" ("ORACLE_SEGMENT", "ORACLE_VALUE", "ACTIVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_GL_MAPPING" FOR "AJC"."AJC_BC_GL_MAPPING"
