
  CREATE TABLE "AJC"."AJC_BC_INC_EXPENSE_RPT_INT" 
   (	"RECORD_ID" NUMBER NOT NULL ENABLE, 
	"INVOICE_TYPE" VARCHAR2(20), 
	"SUPPLIER_NAME" VARCHAR2(240), 
	"SUPPLIER_NUMBER" VARCHAR2(30), 
	"SUPPLIER_SITE_CODE" VARCHAR2(15), 
	"INVOICE_DATE" VARCHAR2(50), 
	"INVOICE_NUMBER" VARCHAR2(50), 
	"CURRENCY_CODE" VARCHAR2(15), 
	"INVOICE_AMOUNT" NUMBER, 
	"DESCRIPTION" VARCHAR2(100), 
	"GL_DATE" VARCHAR2(50), 
	"LINE_NUM" NUMBER(15,0), 
	"LINE_TYPE" VARCHAR2(25), 
	"LINE_AMOUNT" NUMBER, 
	"DISTR_ACCOUNT" VARCHAR2(250), 
	"WORKSHEET_NUMBER" VARCHAR2(10), 
	"INVOICE_IMAGE_URL" VARCHAR2(2048), 
	"REIMBURSE_FLAG" VARCHAR2(20), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"STATUS" VARCHAR2(25), 
	"ORG_ID" NUMBER, 
	"RESP_ID" NUMBER, 
	"ORACLE_SUPPLIER_NUM" VARCHAR2(30), 
	"ORACLE_SUPPLIER_SITE_CODE" VARCHAR2(15), 
	"ORACLE_INVOICE_NUM" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_INC_EXPENSE_RPT_INT" FOR "AJC"."AJC_BC_INC_EXPENSE_RPT_INT"
