
  CREATE TABLE "AJC"."AJC_BC_ABBYY_INV_WS" 
   (	"REQUEST_ID" NUMBER, 
	"INVOICEID" NUMBER, 
	"INVOICENO" VARCHAR2(50), 
	"LINENO" VARCHAR2(10), 
	"WS_URL" VARCHAR2(500), 
	"WS_BODY" CLOB, 
	"WS_RESPONSE" CLOB, 
	"STATUS" VARCHAR2(10), 
	"CREATION_DATE" DATE, 
	"WORKSHEETNO" VARCHAR2(240), 
	"DESCRIPTION" VARCHAR2(240)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("WS_BODY") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("WS_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_ABBYY_INV_WS" FOR "AJC"."AJC_BC_ABBYY_INV_WS"
