
  CREATE TABLE "AJC"."AJC_BC_FA_FIXED_ASSETS_DEPRN" 
   (	"ASSET_ID" NUMBER, 
	"BOOK_TYPE_CODE" VARCHAR2(30), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"NO" VARCHAR2(20), 
	"DEPRECIATION_BOOK_CODE" VARCHAR2(200), 
	"DEPRECIATION_METHOD" VARCHAR2(200), 
	"DEPRECIATION_STARTING_DATE" VARCHAR2(10), 
	"STRAIGHT_LINE_PERC" NUMBER, 
	"NO_OF_DEPRECIATION_YEARS" NUMBER, 
	"NO_OF_DEPRECIATION_MONTHS" NUMBER, 
	"FIXED_DEPR_AMOUNT" NUMBER, 
	"DECLINING_BALANCE_PERC" NUMBER, 
	"DEPRECIATION_TABLE_CODE" VARCHAR2(100), 
	"FINAL_ROUNDING_AMOUNT" NUMBER, 
	"ENDING_BOOK_VALUE" NUMBER, 
	"FA_POSTING_GROUP" VARCHAR2(100), 
	"DEPRECIATION_ENDING_DATE" VARCHAR2(10), 
	"ACQUISITION_DATE" VARCHAR2(10), 
	"GL_ACQUISITION_DATE" VARCHAR2(10), 
	"DISPOSAL_DATE" VARCHAR2(10), 
	"LAST_ACQUISITION_COST_DATE" VARCHAR2(10), 
	"LAST_DEPRECIATION_DATE" VARCHAR2(10), 
	"LAST_WRITE_DOWN_DATE" VARCHAR2(10), 
	"LAST_APPRECIATION_DATE" VARCHAR2(10), 
	"LAST_CUSTOM_1_DATE" VARCHAR2(10), 
	"LAST_CUSTOM_2_DATE" VARCHAR2(10), 
	"LAST_SALVAGE_VALUE_DATE" VARCHAR2(10), 
	"FA_EXCHANGE_RATE" NUMBER, 
	"FIXED_DEPR_AMOUNT_BELOW_ZERO" NUMBER, 
	"LAST_DATE_MODIFIED" VARCHAR2(10), 
	"FIRST_USER_DEFINED_DEPR_DATE" VARCHAR2(10), 
	"USE_FA_LEDGER_CHECK" VARCHAR2(10), 
	"LAST_MAINTENANCE_DATE" VARCHAR2(10), 
	"DEPR_BELOW_ZERO_PERC" NUMBER, 
	"PROJECTED_DISPOSAL_DATE" VARCHAR2(10), 
	"PROJECTED_PROCEEDS_ON_DISPOSAL" NUMBER, 
	"DEPR_STARTING_DATE_CUSTOM_1" VARCHAR2(10), 
	"DEPR_ENDING_DATE_CUSTOM_1" VARCHAR2(10), 
	"ACCUM_DEPR_PERC_CUSTOM_1" NUMBER, 
	"DEPR_THIS_YEAR_PERC_CUSTOM_1" NUMBER, 
	"PROPERTY_CLASS_CUSTOM_1" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(100), 
	"MAIN_ASSET_COMPONENT" VARCHAR2(100), 
	"COMPONENT_OF_MAIN_ASSET" VARCHAR2(100), 
	"FA_ADD_CURRENCY_FACTOR" NUMBER, 
	"USE_HALF_YEAR_CONVENTION" VARCHAR2(10), 
	"USE_DB_PERC_FIRST_FISCAL_YEAR" VARCHAR2(10), 
	"TEMP_ENDING_DATE" VARCHAR2(10), 
	"TEMP_FIXED_DEPR_AMOUNT" NUMBER, 
	"IGNORE_DEF_ENDING_BOOK_VALUE" VARCHAR2(10), 
	"DEFAULT_FA_DEPRECIATION_BOOK" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_FA_FIXED_ASSETS_DEPRN" FOR "AJC"."AJC_BC_FA_FIXED_ASSETS_DEPRN"
