
  CREATE TABLE "AJC"."AJC_BC_AR_NOTES" 
   (	"SYSTEM_ID" VARCHAR2(100), 
	"ORG_ID" NUMBER, 
	"NOTE_ID" NUMBER, 
	"NOTE_TYPE" VARCHAR2(30), 
	"TEXT" VARCHAR2(4000), 
	"CUSTOMER_NUMBER" VARCHAR2(30), 
	"CUSTOMER_NAME" VARCHAR2(50), 
	"CUSTOMER_ID" NUMBER, 
	"TRX_NUMBER" VARCHAR2(60), 
	"DOCUMENT_TYPE" VARCHAR2(100), 
	"CUSTOMER_TRX_ID" NUMBER, 
	"STATUS" VARCHAR2(10), 
	"MESSAGE" VARCHAR2(2000), 
	"CREATION_DATE" DATE, 
	"REQUEST_ID" NUMBER, 
	"COMPANY" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "AJC"."AJC_BC_AR_NOTES_NOTE_ID_I1" ON "AJC"."AJC_BC_AR_NOTES" ("NOTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJC_BC_AR_NOTES_SYSTEM_ID_I2" ON "AJC"."AJC_BC_AR_NOTES" ("SYSTEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_AR_NOTES" FOR "AJC"."AJC_BC_AR_NOTES"
