
  CREATE TABLE "AJC"."AJC_BC_IC_VENDORS" 
   (	"VENDOR_NUMBER" VARCHAR2(30), 
	"VENDOR_NAME" VARCHAR2(100)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJC_BC_ICV_VN_I1" ON "AJC"."AJC_BC_IC_VENDORS" ("VENDOR_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJC_BC_IC_VENDORS" FOR "AJC"."AJC_BC_IC_VENDORS"
