
  CREATE TABLE "AJC"."AJCL_BC_LBX_RCP_APPLICATIONS" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"RECEIPTENTRYNO" NUMBER, 
	"DOCUMENTNO" VARCHAR2(20), 
	"CUSTOMERNO" VARCHAR2(20), 
	"CUSTOMERNAME" VARCHAR2(100), 
	"CURRENCYCODE" VARCHAR2(10), 
	"POSTINGDATE" VARCHAR2(10), 
	"APPLIESTODOCTYPE" VARCHAR2(20), 
	"APPLIESTOENTRYNO" NUMBER, 
	"APPLIESTOTRXID" NUMBER, 
	"APPLIESTODOCNO" VARCHAR2(20), 
	"AMOUNTTOAPPLY" NUMBER, 
	"APPLICATIONENTRYNO" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"JSON_DATA" CLOB, 
	"JSON_DATA_RESPONSE" CLOB, 
	"STATUS" VARCHAR2(20), 
	"ERROR_MESSAGE" VARCHAR2(2000), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"JOURNAL_BATCH_NAME" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("JSON_DATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("JSON_DATA_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_LRA_I3" ON "AJC"."AJCL_BC_LBX_RCP_APPLICATIONS" ("REQUEST_ID", "BC_ENVIRONMENT", "JOURNAL_BATCH_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_LRA_I1" ON "AJC"."AJCL_BC_LBX_RCP_APPLICATIONS" ("REQUEST_ID", "BC_ENVIRONMENT", "STATUS", "RECEIPTENTRYNO", "APPLIESTOENTRYNO", "JOURNAL_BATCH_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_LRA_I2" ON "AJC"."AJCL_BC_LBX_RCP_APPLICATIONS" ("REQUEST_ID", "BC_ENVIRONMENT", "STATUS", "RECEIPTENTRYNO", "APPLIESTOENTRYNO", "CUSTOMERNO", "JOURNAL_BATCH_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_LBX_RCP_APPLICATIONS" FOR "AJC"."AJCL_BC_LBX_RCP_APPLICATIONS"
