
  CREATE TABLE "AJC"."AJCL_BC_LBX_RECEIPTS" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"LOCKBOXID" NUMBER, 
	"LOCKBOXRECEIPTNUMBER" VARCHAR2(50), 
	"CUSTOMERNO" VARCHAR2(20), 
	"CUSTOMERNAME" VARCHAR2(100), 
	"POSTINGDATE" VARCHAR2(10), 
	"CURRENCYCODE" VARCHAR2(10), 
	"AMOUNT" NUMBER, 
	"COMMENTS" VARCHAR2(250), 
	"CUSTOMERBANKABA" VARCHAR2(30), 
	"CUSTOMERBANKACCOUNT" VARCHAR2(30), 
	"ACHWIREBANKCUSTCODENAME" VARCHAR2(80), 
	"TYPEOFRECEIPT" VARCHAR2(30), 
	"DOCUMENTNO" VARCHAR2(20), 
	"ENTRYNO" NUMBER, 
	"ORIGINALCUSTOMERNO" VARCHAR2(20), 
	"ORIGINALCUSTOMERNAME" VARCHAR2(100), 
	"REQUEST_ID" NUMBER, 
	"JSON_DATA" CLOB, 
	"JSON_DATA_RESPONSE" CLOB, 
	"STATUS" VARCHAR2(20), 
	"ERROR_MESSAGE" VARCHAR2(2000), 
	"PAYMENT_NUM" VARCHAR2(25), 
	"PAYMENT_DATE" VARCHAR2(25), 
	"PAYOR_ACCOUNT_NUM" VARCHAR2(25), 
	"ORIGINATING_BANK_ABA" VARCHAR2(25), 
	"DATA_PAYMENT_LINE_NUM" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"JOURNAL_BATCH_NAME" VARCHAR2(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("JSON_DATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("JSON_DATA_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_LR_I1" ON "AJC"."AJCL_BC_LBX_RECEIPTS" ("STATUS", "LOCKBOXID", "REQUEST_ID", "BC_ENVIRONMENT", "JOURNAL_BATCH_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_LR_I2" ON "AJC"."AJCL_BC_LBX_RECEIPTS" ("STATUS", "ENTRYNO", "REQUEST_ID", "BC_ENVIRONMENT", "JOURNAL_BATCH_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_LR_I3" ON "AJC"."AJCL_BC_LBX_RECEIPTS" ("STATUS", "REQUEST_ID", "BC_ENVIRONMENT", "JOURNAL_BATCH_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_LR_I4" ON "AJC"."AJCL_BC_LBX_RECEIPTS" ("LOCKBOXID", "BC_ENVIRONMENT", "REQUEST_ID", "JOURNAL_BATCH_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_LR_I5" ON "AJC"."AJCL_BC_LBX_RECEIPTS" ("REQUEST_ID", "BC_ENVIRONMENT", "JOURNAL_BATCH_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_LR_I6" ON "AJC"."AJCL_BC_LBX_RECEIPTS" ("BC_ENVIRONMENT", "ENTRYNO", "JOURNAL_BATCH_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_LR_I7" ON "AJC"."AJCL_BC_LBX_RECEIPTS" ("ENTRYNO", "BC_ENVIRONMENT", "REQUEST_ID", "JOURNAL_BATCH_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_LR_U1" ON "AJC"."AJCL_BC_LBX_RECEIPTS" ("LOCKBOXID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_LBX_RECEIPTS" FOR "AJC"."AJCL_BC_LBX_RECEIPTS"
