
  CREATE TABLE "AJC"."AJCL_BC_TRV_GL_LINES" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"JOURNALTEMPLATENAME" VARCHAR2(100), 
	"JOURNALBATCHNAME" VARCHAR2(100), 
	"DOCUMENTNO" VARCHAR2(100), 
	"POSTINGDATE" VARCHAR2(10), 
	"USERJESOURCENAME" VARCHAR2(100), 
	"USERJECATEGORYNAME" VARCHAR2(100), 
	"ACCOUNT" VARCHAR2(100), 
	"COMPANY" VARCHAR2(100), 
	"DEPARTMENT" VARCHAR2(100), 
	"DESTINATION" VARCHAR2(100), 
	"OFFICE" VARCHAR2(100), 
	"ORIGIN" VARCHAR2(100), 
	"DIVISION" VARCHAR2(100), 
	"CURRENCYCODE" VARCHAR2(15), 
	"CURRENCYCONVERSIONDATE" VARCHAR2(10), 
	"CURRENCYCONVERSIONRATE" NUMBER, 
	"CURRENCYCONVERSIONTYPE" VARCHAR2(20), 
	"ENTEREDDR" NUMBER, 
	"ENTEREDCR" NUMBER, 
	"DESCRIPTION" VARCHAR2(200), 
	"WORKSHEETNUMBER" VARCHAR2(100), 
	"ORACLELINENO" NUMBER, 
	"JELINEID" NUMBER, 
	"DFF_INVOICE_NUM" VARCHAR2(100), 
	"DFF_PO_NUM" VARCHAR2(100), 
	"DFF_CUSTOMER_CARRIER_ACCT_NUM" VARCHAR2(100), 
	"DFF_ORACLE_VENDOR_NUMBER" VARCHAR2(100), 
	"DFF_ORACLE_VENDOR_NAME" VARCHAR2(100), 
	"DFF_XML_FILE_NAME" VARCHAR2(100), 
	"DFF_ORACLE_XML_RUN_ID" VARCHAR2(100), 
	"DFF_XML_FILE_DATE" VARCHAR2(100), 
	"DFF_LOAD_ID" VARCHAR2(100), 
	"DFF_ITEM_SEQUENCE" VARCHAR2(100), 
	"DFF_EDI_ITEM_CODE" VARCHAR2(100), 
	"DFF_DELIVERY_DATE" VARCHAR2(100), 
	"DFF_ORDER_ID" VARCHAR2(30), 
	"JSON_NUMBER" NUMBER, 
	"STATUS" VARCHAR2(25), 
	"ERROR_MESSAGE" VARCHAR2(1000), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"REQUEST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_TRV_GLL_I1" ON "AJC"."AJCL_BC_TRV_GL_LINES" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_TRV_GLL_I2" ON "AJC"."AJCL_BC_TRV_GL_LINES" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_TRV_GLL_I3" ON "AJC"."AJCL_BC_TRV_GL_LINES" ("DOCUMENTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_TRV_GLL_I4" ON "AJC"."AJCL_BC_TRV_GL_LINES" ("ORACLELINENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_TRV_GLL_I5" ON "AJC"."AJCL_BC_TRV_GL_LINES" ("BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_TRV_GL_LINES" FOR "AJC"."AJCL_BC_TRV_GL_LINES"
