
  CREATE TABLE "AJC"."AJCL_BC_POSTED_SD_HEADERS" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"SYSTEMID" VARCHAR2(200), 
	"ENTRYNO" NUMBER, 
	"TRANSACTIONNO" VARCHAR2(20), 
	"TRANSACTIONNO2" VARCHAR2(20), 
	"TRANSACTIONNO3" VARCHAR2(20), 
	"INVOICEREFERENCE1" NUMBER, 
	"INVOICEREFERENCE2" NUMBER, 
	"SOURCE" VARCHAR2(3), 
	"CLASS" VARCHAR2(3), 
	"AMOUNT" NUMBER, 
	"REMAININGAMOUNT" NUMBER, 
	"APPLIESTODOCNO" VARCHAR2(20), 
	"APPLIESTODOCTYPE" VARCHAR2(20), 
	"BILLTOCUSTOMERNAME" VARCHAR2(100), 
	"BILLTOCUSTOMERNO" VARCHAR2(20), 
	"BILLTOADDRESS" VARCHAR2(100), 
	"BILLTOADDRESS2" VARCHAR2(50), 
	"BILLTOADDRESS3" VARCHAR2(50), 
	"TERMNAME" VARCHAR2(10), 
	"DUEDATE" VARCHAR2(10), 
	"CURRENCYCODE" VARCHAR2(10), 
	"PURCHASEORDER" VARCHAR2(35), 
	"COMPANY" VARCHAR2(20), 
	"ACCOUNT" VARCHAR2(20), 
	"DEPARTMENT" VARCHAR2(20), 
	"DESTINATION" VARCHAR2(20), 
	"OFFICE" VARCHAR2(20), 
	"ORIGIN" VARCHAR2(20), 
	"DIVISION" VARCHAR2(20), 
	"WORKSHEETNO" VARCHAR2(20), 
	"IESINVOICECOMPANY" VARCHAR2(100), 
	"IESINVOICENUMBER" VARCHAR2(100), 
	"IESNUMBER" VARCHAR2(100), 
	"CSAHOUSEBILL" VARCHAR2(100), 
	"CSAMAXPKSEQNO" VARCHAR2(100), 
	"CSACUSTOMERVENDORNO" VARCHAR2(100), 
	"CSASEQNUM" VARCHAR2(100), 
	"CSAFILEEXTRACTNUMBER" VARCHAR2(100), 
	"TRVSHIPPINGORDER" VARCHAR2(100), 
	"TRVINVOICENUM" VARCHAR2(100), 
	"TRVCUSTOMERCARRIERACCTNUM" VARCHAR2(100), 
	"TRVXMLFILENAME" VARCHAR2(100), 
	"TRVORACLEXMLRUNID" VARCHAR2(100), 
	"TRVXMLFILEDATE" VARCHAR2(100), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I17" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("TRVSHIPPINGORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I18" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("INVOICEREFERENCE1", "INVOICEREFERENCE2", "BC_ENVIRONMENT", "CLASS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I19" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("ENTRYNO", "BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I20" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("ENTRYNO", "APPLIESTODOCNO", "BILLTOCUSTOMERNO", "BC_ENVIRONMENT", "CLASS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I9" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("APPLIESTODOCTYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I10" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("BILLTOCUSTOMERNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I11" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("COMPANY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I12" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("ENTRYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I13" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("WORKSHEETNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I14" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("PURCHASEORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I15" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("REMAININGAMOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I1" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("SYSTEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I2" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("TRANSACTIONNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I3" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("TRANSACTIONNO2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I4" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("TRANSACTIONNO3") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I5" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("INVOICEREFERENCE1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I6" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("INVOICEREFERENCE2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I7" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("CLASS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDH_I8" ON "AJC"."AJCL_BC_POSTED_SD_HEADERS" ("APPLIESTODOCNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_POSTED_SD_HEADERS" FOR "AJC"."AJCL_BC_POSTED_SD_HEADERS"
