
  CREATE TABLE "AJC"."AJCL_BC_IES_AR_LINES" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"TRANSACTIONNO" VARCHAR2(20), 
	"TRANSACTIONDATE" VARCHAR2(10), 
	"CLASS" VARCHAR2(20), 
	"TERMNAME" VARCHAR2(200), 
	"TERMDUEDATE" VARCHAR2(10), 
	"GLDATE" VARCHAR2(10), 
	"INVOICECURRENCYCODE" VARCHAR2(15), 
	"EXCHANGEDATE" VARCHAR2(10), 
	"EXCHANGERATE" NUMBER, 
	"EXCHANGERATETYPE" VARCHAR2(100), 
	"PURCHASEORDER" VARCHAR2(100), 
	"BILLTOCUSTOMERID" NUMBER, 
	"BILLTOCUSTOMERNAME" VARCHAR2(150), 
	"BILLTOCUSTOMERNO" VARCHAR2(50), 
	"BILLTOADDRESS1" VARCHAR2(150), 
	"BILLTOADDRESS2" VARCHAR2(150), 
	"BILLTOADDRESS3" VARCHAR2(150), 
	"HEADER_COMPANY" VARCHAR2(200), 
	"HEADER_ACCOUNT" VARCHAR2(200), 
	"HEADER_DEPARTMENT" VARCHAR2(200), 
	"HEADER_DESTINATION" VARCHAR2(200), 
	"HEADER_ORIGIN" VARCHAR2(200), 
	"HEADER_OFFICE" VARCHAR2(200), 
	"HEADER_INTERCOMPANY" VARCHAR2(200), 
	"HEADER_DIVISION" VARCHAR2(200), 
	"HEADER_WORKSHEET" VARCHAR2(200), 
	"APPLIESTODOCTYPE" VARCHAR2(20), 
	"APPLIESTODOCNO" VARCHAR2(50), 
	"OVERRIDEFLAG" VARCHAR2(10), 
	"COMMENTSAJC_INE" VARCHAR2(200), 
	"FINANCIAL_PARTY" VARCHAR2(100), 
	"DFF_INVOICE_COMPANY" VARCHAR2(200), 
	"DFF_INVOICE_NUMBER" VARCHAR2(200), 
	"DFF_IES_NUMBER" VARCHAR2(200), 
	"DFF_INVOICE_LINE" VARCHAR2(200), 
	"DFF_PICKUP_DATE" VARCHAR2(10), 
	"DFF_ETD" VARCHAR2(10), 
	"DFF_ETA" VARCHAR2(10), 
	"DFF_DESTINATION" VARCHAR2(200), 
	"DFF_ORIGIN" VARCHAR2(200), 
	"LINENO" NUMBER, 
	"DESCRIPTION" VARCHAR2(200), 
	"QUANTITY" NUMBER, 
	"UNITSELLINGPRICE" NUMBER, 
	"EXTENDEDAMOUNT" NUMBER, 
	"ACCOUNTEDAMOUNT" NUMBER, 
	"LINE_COMPANY" VARCHAR2(200), 
	"LINE_ACCOUNT" VARCHAR2(200), 
	"LINE_DEPARTMENT" VARCHAR2(200), 
	"LINE_DESTINATION" VARCHAR2(200), 
	"LINE_ORIGIN" VARCHAR2(200), 
	"LINE_OFFICE" VARCHAR2(200), 
	"LINE_INTERCOMPANY" VARCHAR2(200), 
	"LINE_DIVISION" VARCHAR2(200), 
	"LINE_WORKSHEET" VARCHAR2(200), 
	"SALESORDERSOURCE" VARCHAR2(200), 
	"SALESORDER" VARCHAR2(200), 
	"SALESORDERREVISION" VARCHAR2(200), 
	"SALESORDERLINE" VARCHAR2(200), 
	"SALESORDERDATE" VARCHAR2(10), 
	"ALREASONMEANING" VARCHAR2(200), 
	"JSON_DATA" CLOB, 
	"JSON_DATA_RESPONSE" CLOB, 
	"ORG_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"ERROR_MESSAGE" VARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("JSON_DATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("JSON_DATA_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_ARL_I1" ON "AJC"."AJCL_BC_IES_AR_LINES" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_ARL_I2" ON "AJC"."AJCL_BC_IES_AR_LINES" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_ARL_I3" ON "AJC"."AJCL_BC_IES_AR_LINES" ("TRANSACTIONNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_ARL_I4" ON "AJC"."AJCL_BC_IES_AR_LINES" ("BILLTOCUSTOMERNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_ARL_I5" ON "AJC"."AJCL_BC_IES_AR_LINES" ("BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_IES_AR_LINES" FOR "AJC"."AJCL_BC_IES_AR_LINES"
