
  CREATE TABLE "AJC"."AJCL_BC_CSA_GL_LINES" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"JOURNALTEMPLATENAME" VARCHAR2(100), 
	"JOURNALBATCHNAME" VARCHAR2(100), 
	"DOCUMENTNO" VARCHAR2(100), 
	"POSTINGDATE" VARCHAR2(10), 
	"USERJESOURCENAME" VARCHAR2(100), 
	"USERJECATEGORYNAME" VARCHAR2(100), 
	"ACCOUNT" VARCHAR2(100), 
	"COMPANY" VARCHAR2(100), 
	"DEPARTMENT" VARCHAR2(100), 
	"DESTINATION" VARCHAR2(100), 
	"OFFICE" VARCHAR2(100), 
	"ORIGIN" VARCHAR2(100), 
	"DIVISION" VARCHAR2(100), 
	"CURRENCYCODE" VARCHAR2(15), 
	"CURRENCYCONVERSIONDATE" VARCHAR2(10), 
	"CURRENCYCONVERSIONRATE" NUMBER, 
	"CURRENCYCONVERSIONTYPE" VARCHAR2(20), 
	"ENTEREDDR" NUMBER, 
	"ENTEREDCR" NUMBER, 
	"DESCRIPTION" VARCHAR2(100), 
	"WORKSHEETNUMBER" VARCHAR2(100), 
	"ORACLELINENO" NUMBER, 
	"JELINEID" NUMBER, 
	"DFF_SEQ_NUMBER" NUMBER, 
	"DFF_ORDER_NO" NUMBER, 
	"DFF_CUSTOMER_VENDOR_NO" VARCHAR2(150), 
	"DFF_ORACLE_VENDOR_NUMBER" VARCHAR2(150), 
	"DFF_ORACLE_VENDOR_NAME" VARCHAR2(150), 
	"DFF_LINE_NUMBER" NUMBER, 
	"DFF_QUANTITY" NUMBER, 
	"DFF_STATION" VARCHAR2(3), 
	"DFF_CREATION_DATE" VARCHAR2(10), 
	"DFF_VENDOR_REFERENCE" VARCHAR2(35), 
	"DFF_SUB_ACCOUNT" VARCHAR2(3), 
	"DFF_DIVISION" VARCHAR2(3), 
	"DFF_EXTRACT_FILE_NUMBER" VARCHAR2(30), 
	"DFF_TRX_CURRENCY_CODE" VARCHAR2(3), 
	"DFF_TRX_ORIG_CURR_AMOUNT" NUMBER, 
	"DFF_TRX_CONTRACT_RATE" NUMBER, 
	"JSON_NUMBER" NUMBER, 
	"STATUS" VARCHAR2(25), 
	"ERROR_MESSAGE" VARCHAR2(1000), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"REQUEST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I4" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("REQUEST_ID", "BC_ENVIRONMENT", "DOCUMENTNO", "USERJESOURCENAME", "USERJECATEGORYNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I5" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("DOCUMENTNO", "REQUEST_ID", "BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I3" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("STATUS", "REQUEST_ID", "BC_ENVIRONMENT", "WORKSHEETNUMBER", "USERJECATEGORYNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I2" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("BC_ENVIRONMENT", "REQUEST_ID", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I1" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("REQUEST_ID", "BC_ENVIRONMENT", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I8" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("REQUEST_ID", "BC_ENVIRONMENT", "WORKSHEETNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I9" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("REQUEST_ID", "BC_ENVIRONMENT", "STATUS", "DFF_EXTRACT_FILE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I10" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("REQUEST_ID", "BC_ENVIRONMENT", "STATUS", "DFF_EXTRACT_FILE_NUMBER", "USERJESOURCENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I11" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("REQUEST_ID", "BC_ENVIRONMENT", "STATUS", "DFF_EXTRACT_FILE_NUMBER", "USERJESOURCENAME", "USERJECATEGORYNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I12" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("REQUEST_ID", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I6" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("REQUEST_ID", "BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GL_I7" ON "AJC"."AJCL_BC_CSA_GL_LINES" ("DOCUMENTNO", "ORACLELINENO", "REQUEST_ID", "BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_CSA_GL_LINES" FOR "AJC"."AJCL_BC_CSA_GL_LINES"
