
  CREATE TABLE "AJC"."AJCL_BC_LOCKBOX_PARAMS" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"DB_NAME" VARCHAR2(100), 
	"LOCAL_FILE_PATH" VARCHAR2(2000), 
	"LOCAL_ARCHIVE_PATH" VARCHAR2(2000), 
	"FILE_NAME" VARCHAR2(2000), 
	"REMOTE_SERVER" VARCHAR2(2000), 
	"REMOTE_PORT" VARCHAR2(2000), 
	"REMOTE_USER" VARCHAR2(2000), 
	"REMOTE_PATH" VARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE UNIQUE INDEX "AJC"."AJCL_BC_LBOX_U1" ON "AJC"."AJCL_BC_LOCKBOX_PARAMS" ("DB_NAME", "BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_LOCKBOX_PARAMS" FOR "AJC"."AJCL_BC_LOCKBOX_PARAMS"
