
  CREATE TABLE "AJC"."AJCL_BC_VENDOR_SITES" 
   (	"SYSTEMID" VARCHAR2(100), 
	"VENDORNO" VARCHAR2(30), 
	"VENDOR_ID" NUMBER, 
	"LEGACYVENDORSITENAME" VARCHAR2(30), 
	"VENDOR_SITE_ID" NUMBER, 
	"CODE" VARCHAR2(200), 
	"NAME" VARCHAR2(200), 
	"ADDRESS" VARCHAR2(200), 
	"ADDRESS2" VARCHAR2(200), 
	"ZIPCODE" VARCHAR2(200), 
	"CITY" VARCHAR2(200), 
	"STATE" VARCHAR2(200), 
	"COUNTRYREGIONCODE" VARCHAR2(200), 
	"CONTACT" VARCHAR2(200), 
	"PHONENO" VARCHAR2(200), 
	"FAXNO" VARCHAR2(200), 
	"EMAIL" VARCHAR2(200), 
	"HOMEPAGE" VARCHAR2(200), 
	"SYSTEMMODIFIEDBY" VARCHAR2(200), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"PROCESSED_DATE" DATE, 
	"STATUS" VARCHAR2(30), 
	"MESSAGE" VARCHAR2(1000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VS_I1" ON "AJC"."AJCL_BC_VENDOR_SITES" ("VENDORNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VS_I2" ON "AJC"."AJCL_BC_VENDOR_SITES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VS_I3" ON "AJC"."AJCL_BC_VENDOR_SITES" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VS_I4" ON "AJC"."AJCL_BC_VENDOR_SITES" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VS_I5" ON "AJC"."AJCL_BC_VENDOR_SITES" ("SYSTEMMODIFIEDBY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_VENDOR_SITES" FOR "AJC"."AJCL_BC_VENDOR_SITES"
