
  CREATE TABLE "AJC"."AJCL_BC_CUST_XREF" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"BP_CUST_ID" NUMBER NOT NULL ENABLE, 
	"BP_CUST_NAME" VARCHAR2(100), 
	"ORACLE_CUST_ID" NUMBER, 
	"SOURCE" VARCHAR2(20), 
	"SOURCE_TYPE" VARCHAR2(15), 
	"ORACLE_VENDOR_ID" NUMBER, 
	"ORACLE_NUMBER" VARCHAR2(30), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE UNIQUE INDEX "AJC"."AJCL_BC_CUST_XREF_U1" ON "AJC"."AJCL_BC_CUST_XREF" ("BC_ENVIRONMENT", "SOURCE", "SOURCE_TYPE", "BP_CUST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_CUST_XREF" FOR "AJC"."AJCL_BC_CUST_XREF"
