
  CREATE TABLE "AJC"."AJCL_BC_CUSTOMERS" 
   (	"SYSTEMID" VARCHAR2(100), 
	"CUSTOMER_NUMBER" VARCHAR2(20), 
	"CUSTOMER_NAME" VARCHAR2(100), 
	"CUSTOMER_ID" NUMBER, 
	"PARTY_ID" NUMBER, 
	"PARTY_NUMBER" VARCHAR2(30), 
	"LOCATION_ID" NUMBER, 
	"PARTY_SITE_ID" NUMBER, 
	"CUST_ACCT_SITE_ID" NUMBER, 
	"BILL_TO_SITE_USE_ID" NUMBER, 
	"SHIP_TO_SITE_USE_ID" NUMBER, 
	"CUSTOMER_TYPE" VARCHAR2(30), 
	"PROFILE_CLASS_ID" NUMBER, 
	"PENDING_BALANCE" NUMBER, 
	"LOB" VARCHAR2(30), 
	"ACCOUNT_STATUS" VARCHAR2(30), 
	"REVIEW_CYCLE" VARCHAR2(30), 
	"LAST_FILE_REVIEW" VARCHAR2(150), 
	"SCORING_MODEL" VARCHAR2(150), 
	"AIG_LIMIT" VARCHAR2(150), 
	"DEACTIVATION_REASON" VARCHAR2(150), 
	"COFACE_LIMIT" VARCHAR2(150), 
	"AJC_DESTINATION_COUNTRY" VARCHAR2(150), 
	"INSURED_COUNTRY" VARCHAR2(150), 
	"ACCOUNT_CREATED" VARCHAR2(150), 
	"BANK_CHARGE" VARCHAR2(150), 
	"ADOP" VARCHAR2(150), 
	"DAE" VARCHAR2(150), 
	"OPEN_ACCT_LIMIT" VARCHAR2(150), 
	"AR_LIMIT" NUMBER, 
	"ORDER_CREDIT_LIMIT" NUMBER, 
	"CUSTOMER_PRIORITY" NUMBER, 
	"CREDIT_HOLD" VARCHAR2(1), 
	"CREDIT_CHECK" VARCHAR2(1), 
	"TOLERANCE" NUMBER, 
	"CREDIT_CLASSIFICATION" VARCHAR2(30), 
	"CREDIT_RATING" VARCHAR2(30), 
	"COLLECTOR" VARCHAR2(30), 
	"COLLECTOR_ID" NUMBER, 
	"SEND_STATEMENTS" VARCHAR2(1), 
	"CREDIT_BALANCE_STATEMENTS" VARCHAR2(1), 
	"CYCLE" VARCHAR2(20), 
	"STATEMENT_CYCLE_ID" NUMBER, 
	"BLOCKED" VARCHAR2(30), 
	"SALESPERSON_CODE" VARCHAR2(100), 
	"SALESPERSON_ID" NUMBER, 
	"PAYMENT_TERMS" VARCHAR2(10), 
	"PAYMENT_TERMS_ID" NUMBER, 
	"PAYMENT_METHOD" VARCHAR2(10), 
	"ADDRESS1" VARCHAR2(100), 
	"ADDRESS2" VARCHAR2(50), 
	"ADDRESS3" VARCHAR2(80), 
	"ADDRESS4" VARCHAR2(80), 
	"COUNTRY" VARCHAR2(10), 
	"CITY" VARCHAR2(60), 
	"STATE" VARCHAR2(30), 
	"ZIP" VARCHAR2(20), 
	"MOBILE" VARCHAR2(30), 
	"PHONE" VARCHAR2(30), 
	"TAX_NO" VARCHAR2(30), 
	"ORG_ID" NUMBER, 
	"ORACLECUSTOMERIDAJCINE" NUMBER, 
	"SYSTEMMODIFIEDBY" VARCHAR2(200), 
	"EXPOSURE_NOTES" VARCHAR2(100), 
	"IESCLIENTIDFINANCIALPARTY" VARCHAR2(12), 
	"GETIESARACCTFROMCUSTOMER" VARCHAR2(1), 
	"MARKETINGCHANNEL" VARCHAR2(30), 
	"INDUSTRYSECTOR" VARCHAR2(30), 
	"STATUS" VARCHAR2(30), 
	"MESSAGE" VARCHAR2(1000), 
	"PROCESSED_DATE" DATE, 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CUST_I1" ON "AJC"."AJCL_BC_CUSTOMERS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CUST_I2" ON "AJC"."AJCL_BC_CUSTOMERS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CUST_I3" ON "AJC"."AJCL_BC_CUSTOMERS" ("CUSTOMER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CUST_I4" ON "AJC"."AJCL_BC_CUSTOMERS" ("CUSTOMER_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CUST_I5" ON "AJC"."AJCL_BC_CUSTOMERS" ("PROCESSED_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CUST_I6" ON "AJC"."AJCL_BC_CUSTOMERS" ("SYSTEMMODIFIEDBY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_CUSTOMERS" FOR "AJC"."AJCL_BC_CUSTOMERS"
