
  CREATE TABLE "AJC"."AJCL_BC_TRV_TPAY_INV_INT" 
   (	"RECORD_ID" NUMBER NOT NULL ENABLE, 
	"PAYMENT_KEY" VARCHAR2(50), 
	"VENDOR_KEY" VARCHAR2(20), 
	"BROKER_REFERENCE_NUM" VARCHAR2(50), 
	"CARRIER_INVOICE_NUM" VARCHAR2(50), 
	"NET_AMOUNT" NUMBER, 
	"PAYMENT_DATE" DATE, 
	"TPAY_PAYMENT_ID" VARCHAR2(20), 
	"MGATE_SO" VARCHAR2(50), 
	"INVOICE_IMAGE_URL" VARCHAR2(2048), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"STATUS" VARCHAR2(25), 
	"ORACLE_VENDOR_ID" NUMBER, 
	"ORACLE_VENDOR_SITE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_TRV_TPAY_INV_INT" FOR "AJC"."AJCL_BC_TRV_TPAY_INV_INT"
