
  CREATE TABLE "AJC"."AJCL_BC_IES_COUNTRY_CODES" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"SYSTEMID" VARCHAR2(100), 
	"COUNTRY_CODE" VARCHAR2(2), 
	"DESCRIPTION" VARCHAR2(240), 
	"ORIGIN" VARCHAR2(20), 
	"DESTINATION" VARCHAR2(20), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_CC_I1" ON "AJC"."AJCL_BC_IES_COUNTRY_CODES" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_CC_I2" ON "AJC"."AJCL_BC_IES_COUNTRY_CODES" ("COUNTRY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_CC_I3" ON "AJC"."AJCL_BC_IES_COUNTRY_CODES" ("ORIGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_CC_I4" ON "AJC"."AJCL_BC_IES_COUNTRY_CODES" ("DESTINATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_CC_I5" ON "AJC"."AJCL_BC_IES_COUNTRY_CODES" ("BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_IES_COUNTRY_CODES" FOR "AJC"."AJCL_BC_IES_COUNTRY_CODES"
