
  CREATE TABLE "AJC"."AJCL_BC_POSTED_SD_LINES" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"SYSTEMID" VARCHAR2(200), 
	"TRANSACTIONNO" VARCHAR2(20), 
	"LINENO" NUMBER, 
	"DESCRIPTION" VARCHAR2(100), 
	"QUANTITY" NUMBER, 
	"AMOUNT" NUMBER, 
	"BILLTOCUSTOMERNO" NUMBER, 
	"COMPANY" VARCHAR2(20), 
	"ACCOUNT" VARCHAR2(20), 
	"DIMENSION_SET_ID" NUMBER, 
	"DEPARTMENT" VARCHAR2(20), 
	"DESTINATION" VARCHAR2(20), 
	"OFFICE" VARCHAR2(20), 
	"ORIGIN" VARCHAR2(20), 
	"DIVISION" VARCHAR2(20), 
	"WORKSHEETNO" VARCHAR2(20), 
	"IESINVOICELINE" VARCHAR2(100), 
	"IESPICKUPDATE" VARCHAR2(100), 
	"IESETD" VARCHAR2(100), 
	"IESETA" VARCHAR2(100), 
	"IESDESTINATION" VARCHAR2(100), 
	"IESORIGIN" VARCHAR2(100), 
	"CSAPKSEQNUMBER" VARCHAR2(100), 
	"CSASEQOFCHARGE" VARCHAR2(100), 
	"CSACREATIONDATE" VARCHAR2(100), 
	"CSAORDERNO" VARCHAR2(100), 
	"CSASTATIONID" VARCHAR2(100), 
	"CSASUBACCOUNT" VARCHAR2(100), 
	"CSADIVISION" VARCHAR2(100), 
	"TRVITEMSEQUENCE" VARCHAR2(100), 
	"TRVMGLOADID" VARCHAR2(100), 
	"TRVEDIITEMCODECHARGETYPE" VARCHAR2(100), 
	"TRVDELIVERYDATE" VARCHAR2(100), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDL_I5" ON "AJC"."AJCL_BC_POSTED_SD_LINES" ("TRVMGLOADID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDL_I1" ON "AJC"."AJCL_BC_POSTED_SD_LINES" ("TRANSACTIONNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDL_I2" ON "AJC"."AJCL_BC_POSTED_SD_LINES" ("LINENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDL_I3" ON "AJC"."AJCL_BC_POSTED_SD_LINES" ("BILLTOCUSTOMERNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PSDL_I4" ON "AJC"."AJCL_BC_POSTED_SD_LINES" ("BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_POSTED_SD_LINES" FOR "AJC"."AJCL_BC_POSTED_SD_LINES"
