
  CREATE TABLE "AJC"."AJCL_BC_AP_TRV_TPAY_LINES" 
   (	"INVOICE_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"INVOICE_LINE_ID" NUMBER(15,0), 
	"LINE_NUMBER" NUMBER(15,0), 
	"LINE_TYPE_LOOKUP_CODE" VARCHAR2(25), 
	"LINE_GROUP_NUMBER" NUMBER, 
	"AMOUNT" NUMBER, 
	"ACCOUNTING_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(240), 
	"AMOUNT_INCLUDES_TAX_FLAG" VARCHAR2(1), 
	"PRORATE_ACROSS_FLAG" VARCHAR2(1), 
	"TAX_CODE" VARCHAR2(15), 
	"FINAL_MATCH_FLAG" VARCHAR2(1), 
	"PO_HEADER_ID" NUMBER, 
	"PO_NUMBER" VARCHAR2(20), 
	"PO_LINE_ID" NUMBER, 
	"PO_LINE_NUMBER" NUMBER, 
	"PO_LINE_LOCATION_ID" NUMBER, 
	"PO_SHIPMENT_NUM" NUMBER, 
	"PO_DISTRIBUTION_ID" NUMBER, 
	"PO_DISTRIBUTION_NUM" NUMBER, 
	"PO_UNIT_OF_MEASURE" VARCHAR2(25), 
	"INVENTORY_ITEM_ID" NUMBER, 
	"ITEM_DESCRIPTION" VARCHAR2(240), 
	"QUANTITY_INVOICED" NUMBER, 
	"SHIP_TO_LOCATION_CODE" VARCHAR2(60), 
	"UNIT_PRICE" NUMBER, 
	"DISTRIBUTION_SET_ID" NUMBER(15,0), 
	"DISTRIBUTION_SET_NAME" VARCHAR2(50), 
	"DIST_CODE_CONCATENATED" VARCHAR2(250), 
	"DIST_CODE_COMBINATION_ID" VARCHAR2(20), 
	"SET_OF_BOOKS_ID" VARCHAR2(10), 
	"SET_OF_BOOKS_NAME" VARCHAR2(240), 
	"COMPANY" VARCHAR2(10), 
	"ACCOUNT" VARCHAR2(20), 
	"ACCOUNT_DESCRIPTION" VARCHAR2(240), 
	"DEPARTMENT" VARCHAR2(10), 
	"PRODUCT" VARCHAR2(10), 
	"DIVISION" VARCHAR2(10), 
	"DESTINATION" VARCHAR2(10), 
	"OFFICE" VARCHAR2(10), 
	"ORIGIN" VARCHAR2(10), 
	"INTERCOMPANY" VARCHAR2(10), 
	"AWT_GROUP_ID" NUMBER(15,0), 
	"AWT_GROUP_NAME" VARCHAR2(25), 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"CREATED_BY" NUMBER(15,0), 
	"CREATION_DATE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE1" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE2" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE3" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE4" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE5" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE6" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE7" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE8" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE9" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE10" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE11" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE12" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE13" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE14" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE15" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE16" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE17" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE18" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE19" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE20" VARCHAR2(150), 
	"PO_RELEASE_ID" NUMBER, 
	"RELEASE_NUM" NUMBER, 
	"BALANCING_SEGMENT" VARCHAR2(25), 
	"COST_CENTER_SEGMENT" VARCHAR2(25), 
	"ACCOUNT_SEGMENT" VARCHAR2(25), 
	"PROJECT_ID" NUMBER(15,0), 
	"TASK_ID" NUMBER(15,0), 
	"EXPENDITURE_TYPE" VARCHAR2(30), 
	"EXPENDITURE_ITEM_DATE" DATE, 
	"EXPENDITURE_ORGANIZATION_ID" NUMBER(15,0), 
	"PROJECT_ACCOUNTING_CONTEXT" VARCHAR2(30), 
	"PA_ADDITION_FLAG" VARCHAR2(1), 
	"PA_QUANTITY" NUMBER(22,5), 
	"USSGL_TRANSACTION_CODE" VARCHAR2(30), 
	"STAT_AMOUNT" NUMBER, 
	"TYPE_1099" VARCHAR2(10), 
	"INCOME_TAX_REGION" VARCHAR2(10), 
	"ASSETS_TRACKING_FLAG" VARCHAR2(1), 
	"PRICE_CORRECTION_FLAG" VARCHAR2(1), 
	"ORG_ID" NUMBER(15,0), 
	"RECEIPT_NUMBER" VARCHAR2(30), 
	"RECEIPT_LINE_NUMBER" VARCHAR2(25), 
	"MATCH_OPTION" VARCHAR2(25), 
	"PACKING_SLIP" VARCHAR2(25), 
	"RCV_TRANSACTION_ID" NUMBER, 
	"PA_CC_AR_INVOICE_ID" NUMBER(15,0), 
	"PA_CC_AR_INVOICE_LINE_NUM" NUMBER(15,0), 
	"REFERENCE_1" VARCHAR2(30), 
	"REFERENCE_2" VARCHAR2(30), 
	"PA_CC_PROCESSED_CODE" VARCHAR2(1), 
	"TAX_RECOVERY_RATE" NUMBER, 
	"TAX_RECOVERY_OVERRIDE_FLAG" VARCHAR2(1), 
	"TAX_RECOVERABLE_FLAG" VARCHAR2(1), 
	"TAX_CODE_OVERRIDE_FLAG" VARCHAR2(1), 
	"TAX_CODE_ID" NUMBER(15,0), 
	"CREDIT_CARD_TRX_ID" NUMBER(15,0), 
	"AWARD_ID" NUMBER(15,0), 
	"VENDOR_ITEM_NUM" VARCHAR2(25), 
	"TAXABLE_FLAG" VARCHAR2(1), 
	"PRICE_CORRECT_INV_NUM" VARCHAR2(50), 
	"EXTERNAL_DOC_LINE_REF" VARCHAR2(240), 
	"PDF_FILE_URL" VARCHAR2(2000), 
	"JSON_DATA" CLOB, 
	"JSON_DATA_RESPONSE" CLOB, 
	"STATUS" VARCHAR2(25), 
	"ERROR_MESSAGE" VARCHAR2(1000), 
	"REQUEST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("JSON_DATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("JSON_DATA_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  CREATE INDEX "AJC"."AJCL_BC_TRV_TPAYL_IID_I3" ON "AJC"."AJCL_BC_AP_TRV_TPAY_LINES" ("INVOICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJCL_BC_TRV_TPAYL_LN_I4" ON "AJC"."AJCL_BC_AP_TRV_TPAY_LINES" ("LINE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJCL_BC_TRV_TPAYL_RID_I1" ON "AJC"."AJCL_BC_AP_TRV_TPAY_LINES" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE INDEX "AJC"."AJCL_BC_TRV_TPAYL_STATUS_I2" ON "AJC"."AJCL_BC_AP_TRV_TPAY_LINES" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_IDX" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_AP_TRV_TPAY_LINES" FOR "AJC"."AJCL_BC_AP_TRV_TPAY_LINES"
