
  CREATE TABLE "AJC"."AJCL_BC_PAYMENT_TERMS" 
   (	"CODE" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(200), 
	"CALCPMTDISCONCRMEMOS" VARCHAR2(20), 
	"COUPLEDTOCRM" VARCHAR2(20), 
	"DISCOUNT" VARCHAR2(20), 
	"DISCOUNTDATECALCULATION" VARCHAR2(20), 
	"DUEDATECALCULATION" VARCHAR2(20), 
	"SATPAYMENTTERM" VARCHAR2(100), 
	"ID" VARCHAR2(100), 
	"LASTMODIFIEDDATETIME" VARCHAR2(100), 
	"ACCOUNTSTATEMENTDUEDAYS" VARCHAR2(100), 
	"TYPE" VARCHAR2(100), 
	"INACTIVE" VARCHAR2(1), 
	"SYSTEMMODIFIEDBY" VARCHAR2(200), 
	"NAME" VARCHAR2(50), 
	"MODULE" VARCHAR2(2), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"PROCESSED_DATE" DATE, 
	"STATUS" VARCHAR2(30), 
	"MESSAGE" VARCHAR2(1000)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PT_I2" ON "AJC"."AJCL_BC_PAYMENT_TERMS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PT_I3" ON "AJC"."AJCL_BC_PAYMENT_TERMS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PT_I4" ON "AJC"."AJCL_BC_PAYMENT_TERMS" ("SYSTEMMODIFIEDBY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_PT_I1" ON "AJC"."AJCL_BC_PAYMENT_TERMS" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_PAYMENT_TERMS" FOR "AJC"."AJCL_BC_PAYMENT_TERMS"
