
  CREATE TABLE "AJC"."AJCL_BC_WORKSHEET_CONTROL" 
   (	"REQUEST_ID" NUMBER, 
	"COUNT" NUMBER, 
	"BC_ENVIRONMENT" VARCHAR2(100), 
	"STATUS" VARCHAR2(10), 
	"JOB_RESPONSE" CLOB, 
	"CREATION_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("JOB_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_WORKSHEET_CONTROL" FOR "AJC"."AJCL_BC_WORKSHEET_CONTROL"
