
  CREATE TABLE "AJC"."AJCL_BC_IFC_CONTROL_TABLE" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"IFC" VARCHAR2(100), 
	"LAST_PROCESSED_DATE" TIMESTAMP (6), 
	"REQUEST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE UNIQUE INDEX "APPS_ORAFSYS"."AJCL_BC_ICT_I1" ON "AJC"."AJCL_BC_IFC_CONTROL_TABLE" ("BC_ENVIRONMENT", "IFC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_IFC_CONTROL_TABLE" FOR "AJC"."AJCL_BC_IFC_CONTROL_TABLE"
