
  CREATE TABLE "AJC"."AJCL_BC_IES_AR_HEADERS" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"COMPANY" VARCHAR2(200), 
	"TRANSACTIONNO" VARCHAR2(20), 
	"TRANSACTIONDATE" VARCHAR2(10), 
	"CLASS" VARCHAR2(20), 
	"TERMNAME" VARCHAR2(200), 
	"TERMDUEDATE" VARCHAR2(10), 
	"GLDATE" VARCHAR2(10), 
	"INVOICECURRENCYCODE" VARCHAR2(15), 
	"EXCHANGEDATE" VARCHAR2(10), 
	"EXCHANGERATE" NUMBER, 
	"EXCHANGERATETYPE" VARCHAR2(100), 
	"PURCHASEORDER" VARCHAR2(100), 
	"AMOUNT" NUMBER, 
	"ACCOUNTEDAMOUNT" NUMBER, 
	"ACCOUNT" VARCHAR2(200), 
	"DEPARTMENT" VARCHAR2(200), 
	"DESTINATION" VARCHAR2(200), 
	"ORIGIN" VARCHAR2(200), 
	"OFFICE" VARCHAR2(200), 
	"INTERCOMPANY" VARCHAR2(200), 
	"DIVISION" VARCHAR2(200), 
	"BILLTOCUSTOMERID" NUMBER, 
	"BILLTOCUSTOMERNAME" VARCHAR2(150), 
	"BILLTOCUSTOMERNO" VARCHAR2(50), 
	"BILLTOADDRESS1" VARCHAR2(150), 
	"BILLTOADDRESS2" VARCHAR2(150), 
	"BILLTOADDRESS3" VARCHAR2(150), 
	"WORKSHEETNO" VARCHAR2(200), 
	"APPLIESTODOCTYPE" VARCHAR2(20), 
	"APPLIESTODOCNO" VARCHAR2(50), 
	"OVERRIDEFLAG" VARCHAR2(10), 
	"COMMENTSAJC_INE" VARCHAR2(200), 
	"FINANCIAL_PARTY" VARCHAR2(100), 
	"DFF_INVOICE_COMPANY" VARCHAR2(200), 
	"DFF_INVOICE_NUMBER" VARCHAR2(200), 
	"DFF_IES_NUMBER" VARCHAR2(200), 
	"REPROCESS" VARCHAR2(1), 
	"JSON_DATA" CLOB, 
	"JSON_DATA_RESPONSE" CLOB, 
	"ORG_ID" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"ERROR_MESSAGE" VARCHAR2(2000)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("JSON_DATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("JSON_DATA_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_AR_I1" ON "AJC"."AJCL_BC_IES_AR_HEADERS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_AR_I2" ON "AJC"."AJCL_BC_IES_AR_HEADERS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_AR_I3" ON "AJC"."AJCL_BC_IES_AR_HEADERS" ("COMPANY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_AR_I4" ON "AJC"."AJCL_BC_IES_AR_HEADERS" ("TRANSACTIONNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_AR_I5" ON "AJC"."AJCL_BC_IES_AR_HEADERS" ("BILLTOCUSTOMERNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_IES_AR_I6" ON "AJC"."AJCL_BC_IES_AR_HEADERS" ("BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_IES_AR_HEADERS" FOR "AJC"."AJCL_BC_IES_AR_HEADERS"
