
  CREATE TABLE "AJC"."AJCL_BC_AR_DM_HEADERS" 
   (	"CUSTOMER_TRX_ID" NUMBER, 
	"COMPANY" VARCHAR2(10), 
	"ORACLE_TRX_NUMBER" VARCHAR2(20), 
	"TRX_NUMBER" VARCHAR2(20), 
	"TRX_DATE" DATE, 
	"CLASS" VARCHAR2(20), 
	"TERM_ID" NUMBER, 
	"TERM_NAME" VARCHAR2(15), 
	"TERM_DUE_DATE" DATE, 
	"GL_DATE" DATE, 
	"INVOICE_CURRENCY_CODE" VARCHAR2(15), 
	"EXCHANGE_DATE" DATE, 
	"EXCHANGE_RATE" NUMBER, 
	"EXCHANGE_RATE_TYPE" VARCHAR2(30), 
	"PURCHASE_ORDER" VARCHAR2(50), 
	"AMOUNT" NUMBER, 
	"ACCOUNTED_AMOUNT" NUMBER, 
	"ACCOUNT" VARCHAR2(20), 
	"DEPARTMENT" VARCHAR2(10), 
	"PRODUCT" VARCHAR2(10), 
	"DESTINATION" VARCHAR2(10), 
	"OFFICE" VARCHAR2(10), 
	"ORIGIN" VARCHAR2(10), 
	"INTERCOMPANY" VARCHAR2(10), 
	"CUSTOMER_NAME" VARCHAR2(50), 
	"CUSTOMER_NUMBER" VARCHAR2(30), 
	"BILL_TO_ADDRESS_1" VARCHAR2(240), 
	"BILL_TO_ADDRESS_2" VARCHAR2(240), 
	"BILL_TO_ADDRESS_3" VARCHAR2(240), 
	"WORKSHEET" VARCHAR2(30), 
	"APPLIES_TO_DOC_TYPE" VARCHAR2(20), 
	"APPLIES_TO_DOC_NO" VARCHAR2(20), 
	"OVERRIDE_FLAG" VARCHAR2(5), 
	"COMMENTS" VARCHAR2(1760), 
	"SOURCE" VARCHAR2(30), 
	"INVOICEREFERENCE1" NUMBER, 
	"INVOICEREFERENCE2" NUMBER, 
	"IESINVOICECOMPANY" VARCHAR2(200), 
	"IESINVOICENUMBER" VARCHAR2(200), 
	"IESNUMBER" VARCHAR2(200), 
	"CSAHOUSEBILL" VARCHAR2(200), 
	"CSAMAXCSAPKSEQNO" VARCHAR2(200), 
	"CSACUSTOMERVENDOR" VARCHAR2(200), 
	"CSASEQNUM" VARCHAR2(200), 
	"CSAFILEEXTRACTNUMBER" VARCHAR2(200), 
	"TRVSHIPPINGORDER" VARCHAR2(200), 
	"TRVINVOICENUM" VARCHAR2(200), 
	"TRVCUSTCARRIERACCTNUM" VARCHAR2(200), 
	"TRVXMLFILENAME" VARCHAR2(200), 
	"TRVORACLEXMLRUNID" VARCHAR2(200), 
	"TRVXMLFILEDATE" VARCHAR2(200), 
	"BC_ENVIRONMENT" VARCHAR2(100), 
	"STATUS" VARCHAR2(100), 
	"ERROR_MESSAGE" VARCHAR2(1000), 
	"JSON_DATA" CLOB, 
	"JSON_DATA_RESPONSE" CLOB, 
	"REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"ORG_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("JSON_DATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("JSON_DATA_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_AR_DM_I1" ON "AJC"."AJCL_BC_AR_DM_HEADERS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_AR_DM_I2" ON "AJC"."AJCL_BC_AR_DM_HEADERS" ("CUSTOMER_TRX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_AR_DM_HEADERS" FOR "AJC"."AJCL_BC_AR_DM_HEADERS"
