
  CREATE TABLE "AJC"."AJCL_BC_IES_ITEMS" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"SYSTEMID" VARCHAR2(100), 
	"CHARGE_TYPE_CODE" VARCHAR2(6), 
	"SUBSTITUTE" VARCHAR2(6), 
	"BUSINESS_LINE" VARCHAR2(2), 
	"INACTIVE_DATE" DATE, 
	"CGS_ACCOUNTNO" VARCHAR2(20), 
	"CGS_COMPANY" VARCHAR2(20), 
	"CGS_DEPARTMENT" VARCHAR2(20), 
	"CGS_DESTINATION" VARCHAR2(20), 
	"CGS_OFFICE" VARCHAR2(20), 
	"CGS_ORIGIN" VARCHAR2(20), 
	"CGS_DIVISION" VARCHAR2(20), 
	"OFFSET_ACCOUNTNO" VARCHAR2(20), 
	"OFFSET_COMPANY" VARCHAR2(20), 
	"OFFSET_DEPARTMENT" VARCHAR2(20), 
	"OFFSET_DESTINATION" VARCHAR2(20), 
	"OFFSET_OFFICE" VARCHAR2(20), 
	"OFFSET_ORIGIN" VARCHAR2(20), 
	"OFFSET_DIVISION" VARCHAR2(20), 
	"REV_ACCOUNTNO" VARCHAR2(20), 
	"REV_COMPANY" VARCHAR2(20), 
	"REV_DEPARTMENT" VARCHAR2(20), 
	"REV_DESTINATION" VARCHAR2(20), 
	"REV_OFFICE" VARCHAR2(20), 
	"REV_ORIGIN" VARCHAR2(20), 
	"REV_DIVISION" VARCHAR2(20), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_II_I1" ON "AJC"."AJCL_BC_IES_ITEMS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_II_I2" ON "AJC"."AJCL_BC_IES_ITEMS" ("CHARGE_TYPE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_II_I3" ON "AJC"."AJCL_BC_IES_ITEMS" ("BUSINESS_LINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_II_I4" ON "AJC"."AJCL_BC_IES_ITEMS" ("SUBSTITUTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_II_I5" ON "AJC"."AJCL_BC_IES_ITEMS" ("BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_IES_ITEMS" FOR "AJC"."AJCL_BC_IES_ITEMS"
