
  CREATE TABLE "AJC"."AJCL_BC_AR_DM_LINES" 
   (	"CUSTOMER_TRX_ID" NUMBER, 
	"CUSTOMER_TRX_LINE_ID" NUMBER, 
	"COMPANY" VARCHAR2(10), 
	"LINE_NUMBER" NUMBER, 
	"DESCRIPTION" VARCHAR2(240), 
	"QUANTITY" NUMBER, 
	"UNIT_SELLING_PRICE" NUMBER, 
	"EXTENDED_AMOUNT" NUMBER, 
	"ACCOUNTED_AMOUNT" NUMBER, 
	"ACCOUNT" VARCHAR2(20), 
	"DEPARTMENT" VARCHAR2(10), 
	"PRODUCT" VARCHAR2(10), 
	"DESTINATION" VARCHAR2(10), 
	"OFFICE" VARCHAR2(10), 
	"ORIGIN" VARCHAR2(10), 
	"INTERCOMPANY" VARCHAR2(10), 
	"SALES_ORDER_SOURCE" VARCHAR2(50), 
	"SALES_ORDER" VARCHAR2(50), 
	"SALES_ORDER_REVISION" NUMBER, 
	"SALES_ORDER_LINE" VARCHAR2(30), 
	"SALES_ORDER_DATE" DATE, 
	"WORKSHEET" VARCHAR2(150), 
	"IESINVOICELINE" VARCHAR2(200), 
	"IESPICKUPDATE" VARCHAR2(10), 
	"IESETD" VARCHAR2(10), 
	"IESETA" VARCHAR2(10), 
	"IESDESTINATION" VARCHAR2(200), 
	"IESORIGIN" VARCHAR2(200), 
	"CSAPKSEQNUMBER" VARCHAR2(200), 
	"CSASEQOFCHARGE" VARCHAR2(200), 
	"CSACREATIONDATE" VARCHAR2(200), 
	"CSAORDERNO" VARCHAR2(200), 
	"CSASTATIONID" VARCHAR2(200), 
	"CSASUBACCOUNT" VARCHAR2(200), 
	"CSADIVISION" VARCHAR2(200), 
	"TRVITEMSEQUENCE" VARCHAR2(200), 
	"TRVMGLOADID" VARCHAR2(200), 
	"TRVEDIITEMCODECHARGETYPE" VARCHAR2(200), 
	"TRVDELIVERYDATE" VARCHAR2(200), 
	"BC_ENVIRONMENT" VARCHAR2(100), 
	"STATUS" VARCHAR2(100), 
	"ERROR_MESSAGE" VARCHAR2(1000), 
	"JSON_DATA" CLOB, 
	"JSON_DATA_RESPONSE" CLOB, 
	"REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("JSON_DATA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("JSON_DATA_RESPONSE") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_ARL_DM_I1" ON "AJC"."AJCL_BC_AR_DM_LINES" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_ARL_DM_I2" ON "AJC"."AJCL_BC_AR_DM_LINES" ("CUSTOMER_TRX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_AR_DM_LINES" FOR "AJC"."AJCL_BC_AR_DM_LINES"
