
  CREATE TABLE "AJC"."AJCL_BC_GEN_JNL_ENTRIES" 
   (	"BC_ENVIRONMENT" VARCHAR2(100), 
	"SYSTEMID" VARCHAR2(100), 
	"SOURCECODE" VARCHAR2(30), 
	"ENTRYNO" NUMBER, 
	"DOCUMENTNO" VARCHAR2(20), 
	"WORKSHEETNO" VARCHAR2(30), 
	"USERJESOURCENAME" VARCHAR2(100), 
	"USERJECATEGORYNAME" VARCHAR2(100), 
	"AMOUNT" NUMBER, 
	"REVERSED" VARCHAR2(10), 
	"REVERSEDENTRYNO" NUMBER, 
	"REVERSEDBYENTRYNO" NUMBER, 
	"JOURNALTEMPLATENAME" VARCHAR2(200), 
	"JOURNALBATCHNAME" VARCHAR2(200), 
	"SOURCE" VARCHAR2(10), 
	"ORACLELINENO" NUMBER, 
	"POSTINGDATE" VARCHAR2(10), 
	"COMPANY" VARCHAR2(200), 
	"DEPARTMENT" VARCHAR2(200), 
	"ACCOUNT" VARCHAR2(200), 
	"DESTINATION" VARCHAR2(200), 
	"OFFICE" VARCHAR2(200), 
	"ORIGIN" VARCHAR2(200), 
	"DIVISION" VARCHAR2(200), 
	"CURRENCYCODE" VARCHAR2(15), 
	"CURRENCYCONVERSIONDATE" VARCHAR2(10), 
	"CURRENCYCONVERSIONRATE" NUMBER, 
	"CURRENCYCONVERSIONTYPE" VARCHAR2(20), 
	"ENTEREDDR" NUMBER, 
	"ENTEREDCR" NUMBER, 
	"DESCRIPTION" VARCHAR2(200), 
	"WORKSHEETNUMBER" VARCHAR2(100), 
	"IESAPFINANCIALPARTY" VARCHAR2(200), 
	"IESORIGAPINTERNAL" VARCHAR2(200), 
	"IESORACLEVENDORNUMBER" VARCHAR2(200), 
	"IESORACLEVENDORNAME" VARCHAR2(200), 
	"IESTRXCURRENCYCODE" VARCHAR2(200), 
	"IESTRXORIGCURRAMOUNT" VARCHAR2(200), 
	"IESTRXCONTRACTRATE" VARCHAR2(200), 
	"CSASEQNUMBER" VARCHAR2(200), 
	"CSAORDERNO" VARCHAR2(200), 
	"CSACUSTOMERVENDORNO" VARCHAR2(200), 
	"CSAORACLEVENDORNUMBER" VARCHAR2(200), 
	"CSAORACLEVENDORNAME" VARCHAR2(200), 
	"CSALINENUMBER" VARCHAR2(200), 
	"CSAQUANTITY" VARCHAR2(200), 
	"CSASTATION" VARCHAR2(200), 
	"CSACREATIONDATE" VARCHAR2(200), 
	"CSAVENDORREFERENCE" VARCHAR2(200), 
	"CSASUBACCOUNT" VARCHAR2(200), 
	"CSADIVISION" VARCHAR2(200), 
	"CSAEXTRACTFILENUMBER" VARCHAR2(200), 
	"CSATRXCURRENCYCODE" VARCHAR2(200), 
	"CSATRXORIGCURRAMOUNT" VARCHAR2(200), 
	"CSATRXCONTRACTRATE" VARCHAR2(200), 
	"TRVINVOICENUM" VARCHAR2(200), 
	"TRVPONUM" VARCHAR2(200), 
	"TRVCUSTOMERCARRIERACCTNUM" VARCHAR2(200), 
	"TRVORACLEVENDORNUMBER" VARCHAR2(200), 
	"TRVORACLEVENDORNAME" VARCHAR2(200), 
	"TRVXMLFILENAME" VARCHAR2(200), 
	"TRVORACLEXMLRUNID" VARCHAR2(200), 
	"TRVXMLFILEDATE" VARCHAR2(200), 
	"TRVLOADID" VARCHAR2(200), 
	"TRVITEMSEQUENCE" VARCHAR2(200), 
	"TRVEDIITEMCODE" VARCHAR2(200), 
	"TRVDELIVERYDATE" VARCHAR2(200), 
	"TRVORDERID" VARCHAR2(200), 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_J_I2" ON "AJC"."AJCL_BC_GEN_JNL_ENTRIES" ("SYSTEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_J_I3" ON "AJC"."AJCL_BC_GEN_JNL_ENTRIES" ("ENTRYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_J_I4" ON "AJC"."AJCL_BC_GEN_JNL_ENTRIES" ("DOCUMENTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_J_I5" ON "AJC"."AJCL_BC_GEN_JNL_ENTRIES" ("WORKSHEETNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_J_I6" ON "AJC"."AJCL_BC_GEN_JNL_ENTRIES" ("USERJESOURCENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_J_I7" ON "AJC"."AJCL_BC_GEN_JNL_ENTRIES" ("USERJECATEGORYNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_J_I8" ON "AJC"."AJCL_BC_GEN_JNL_ENTRIES" ("REVERSED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_J_I9" ON "AJC"."AJCL_BC_GEN_JNL_ENTRIES" ("REVERSEDENTRYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_J_I10" ON "AJC"."AJCL_BC_GEN_JNL_ENTRIES" ("REVERSEDBYENTRYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_J_I11" ON "AJC"."AJCL_BC_GEN_JNL_ENTRIES" ("SOURCECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_J_I1" ON "AJC"."AJCL_BC_GEN_JNL_ENTRIES" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_GEN_JNL_ENTRIES" FOR "AJC"."AJCL_BC_GEN_JNL_ENTRIES"
