
  CREATE TABLE "AJC"."AJCL_BC_CSA_GL_DETAIL_REPORT" 
   (	"SEQ" NUMBER, 
	"BC_ENVIRONMENT" VARCHAR2(100), 
	"DFF_EXTRACT_FILE_NUMBER" VARCHAR2(30), 
	"USERJESOURCENAME" VARCHAR2(100), 
	"USERJECATEGORYNAME" VARCHAR2(100), 
	"WORKSHEETNUMBER" VARCHAR2(100), 
	"ENTEREDDR" NUMBER, 
	"ENTEREDCR" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER(15,0), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER(15,0), 
	"REQUEST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GLDR_I1" ON "AJC"."AJCL_BC_CSA_GL_DETAIL_REPORT" ("BC_ENVIRONMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GLDR_I2" ON "AJC"."AJCL_BC_CSA_GL_DETAIL_REPORT" ("DFF_EXTRACT_FILE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GLDR_I3" ON "AJC"."AJCL_BC_CSA_GL_DETAIL_REPORT" ("USERJESOURCENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GLDR_I4" ON "AJC"."AJCL_BC_CSA_GL_DETAIL_REPORT" ("USERJECATEGORYNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GLDR_I5" ON "AJC"."AJCL_BC_CSA_GL_DETAIL_REPORT" ("WORKSHEETNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GLDR_I6" ON "AJC"."AJCL_BC_CSA_GL_DETAIL_REPORT" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_CSA_GLDR_I7" ON "AJC"."AJCL_BC_CSA_GL_DETAIL_REPORT" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_CSA_GL_DETAIL_REPORT" FOR "AJC"."AJCL_BC_CSA_GL_DETAIL_REPORT"
