
  CREATE TABLE "AJC"."AJCL_BC_APIS" 
   (	"ENTITY" VARCHAR2(100), 
	"SUBENTITY" VARCHAR2(100), 
	"API" VARCHAR2(100), 
	"API_PUBLISHER" VARCHAR2(100), 
	"API_GROUP" VARCHAR2(100), 
	"API_VERSION" VARCHAR2(10), 
	"GET" VARCHAR2(1), 
	"POST" VARCHAR2(1), 
	"PATCH" VARCHAR2(1), 
	"DEL" VARCHAR2(1), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE UNIQUE INDEX "AJC"."AJCL_BC_APIS_U1" ON "AJC"."AJCL_BC_APIS" ("ENTITY", "SUBENTITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_APIS" FOR "AJC"."AJCL_BC_APIS"
