
  CREATE TABLE "AJC"."AJCL_BC_VENDORS" 
   (	"SYSTEMID" VARCHAR2(100), 
	"SEGMENT1" VARCHAR2(30), 
	"VENDOR_NAME" VARCHAR2(240), 
	"VAT_REGISTRATION_NUM" VARCHAR2(20), 
	"PAYMENT_TERMS" VARCHAR2(50), 
	"TERMS_ID" NUMBER, 
	"VENDOR_ID" NUMBER, 
	"BLOCKED" VARCHAR2(50), 
	"PAY_GROUP" VARCHAR2(50), 
	"COMPANY" VARCHAR2(50), 
	"ORG_ID" NUMBER, 
	"ADDRESS_LINE1" VARCHAR2(100), 
	"ADDRESS_LINE2" VARCHAR2(50), 
	"COUNTRY" VARCHAR2(10), 
	"CITY" VARCHAR2(30), 
	"ZIP" VARCHAR2(20), 
	"EMAIL_ADDRESS" VARCHAR2(80), 
	"VENDOR_SITE_CODE" VARCHAR2(30), 
	"VENDOR_SITE_ID" NUMBER, 
	"PAYMENT_METHOD" VARCHAR2(50), 
	"ORGANIZATION_TYPE" VARCHAR2(150), 
	"ATIS_VALID_VENDOR" VARCHAR2(150), 
	"SAD" VARCHAR2(150), 
	"AJC_KINGDEE_TRANSLATED_NAME" VARCHAR2(150), 
	"AJC_AP_REVALIDATION_EXCLUDE" VARCHAR2(150), 
	"PAYMENT_CURRENCY" VARCHAR2(15), 
	"AJC_COUNTRY_CODE" VARCHAR2(150), 
	"AJC_PARENT_SITE_CREDIT_LIMIT" VARCHAR2(150), 
	"AJC_CREDIT_LIMIT_AMOUNT" VARCHAR2(150), 
	"AJC_PREPAY_CREDIT_LIMIT_AMOUNT" VARCHAR2(150), 
	"SYSTEMMODIFIEDBY" VARCHAR2(200), 
	"ORACLEVENDORIDAJCGINE" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"CREATION_DATE" DATE, 
	"PROCESSED_DATE" DATE, 
	"STATUS" VARCHAR2(30), 
	"MESSAGE" VARCHAR2(1000), 
	"STATE" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 40960 NEXT 40960 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VENDORS_I2" ON "AJC"."AJCL_BC_VENDORS" ("REQUEST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VENDORS_I3" ON "AJC"."AJCL_BC_VENDORS" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VENDORS_I4" ON "AJC"."AJCL_BC_VENDORS" ("SYSTEMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VENDORS_I5" ON "AJC"."AJCL_BC_VENDORS" ("SEGMENT1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VENDORS_I6" ON "AJC"."AJCL_BC_VENDORS" ("PROCESSED_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VENDORS_I7" ON "AJC"."AJCL_BC_VENDORS" ("SYSTEMMODIFIEDBY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VENDORS_I8" ON "AJC"."AJCL_BC_VENDORS" ("VENDOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE INDEX "APPS_ORAFSYS"."AJCL_BC_VENDORS_I1" ON "AJC"."AJCL_BC_VENDORS" ("VENDOR_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 

  CREATE OR REPLACE EDITIONABLE SYNONYM "APPS_ORAFSYS"."AJCL_BC_VENDORS" FOR "AJC"."AJCL_BC_VENDORS"
