CREATE OR REPLACE PACKAGE BODY              AJC_BC_AR_CLE_PKG 

AS

    /*******************************************************************************

    NAME     : AJC_BC_AR_CLE_PKG

    PURPOSE  : Package to download the AR information from Customer Ledger Entry from BC into a internal tables

    TEAM OWNER:  Apps Support

    REVISIONS:

    Ver       Date          Author               Description

    -------------------------------------------------------------------------------

    1.0       Jul-2024      Aura Hernandez       1. Creation of the package

    1.5       May-2025      Ivan Tazelaar        1. Adds support for pagination

                                                 2. Adds basic log (UTL_LOG)

	1.5.1     Apr-2026      Aura Hernandez       Adding a validation to get the information only for the companies 01,18,23

    ********************************************************************************/

    --

    CONST_PACKAGE_NAME      VARCHAR2(100) := 'AJC_BC_AR_CLE_PKG';

    --

    g_credential_static_id  VARCHAR2(200) := AJC_BC_WS_UTILS_PKG.GET_PARAMETER_F ( 'CREDENTIAL_STATIC_ID' ); --'BC_Prod';

	g_token_url             varchar2(4000):= AJC_BC_WS_UTILS_PKG.GET_PARAMETER_F ( 'TOKEN_URL' ); --'http://lbdck.ajc.bz:8085/bc/d177100e-4225-4db2-a0af-d7a0feae584f/oauth2/v2.0/token';

    g_environment           varchar2(15)  ;

    --

    g_execution_id          NUMBER;



    PROCEDURE GET_ENVIRONMENT (p_environment out varchar2 )

    AS

    BEGIN

        SELECT OMS.ADM_SETTING_PKG.GET_SETTING_VALUE

                    (

                    p_setting_key => 'BC.ENVIRONMENT'||CASE WHEN NOT UPPER(NAME) = 'PROD' THEN '.DEV' END

                    ) 

          INTO p_environment

        FROM V$DATABASE;

    END;



	----

	/*

	CREATE TABLE OMS.ADM_LOG_CLOB (

		TK_ADM_LOG       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,

		PACKAGE_NAME     VARCHAR2(500) NOT NULL,

		PROCESS_NAME     VARCHAR2(500) NOT NULL,

		MESSAGE          VARCHAR2(2000),

		CDATA            CLOB,

		CREATION_DATE    TIMESTAMP,

		CREATED_BY       VARCHAR2(100),

		CONSTRAINT PK_ADM_LOG_CLOB PRIMARY KEY (TK_ADM_LOG)

	);*/



	PROCEDURE PR_INS_LOG_CLOB(P_PACKAGE_NAME IN VARCHAR2, P_PROCESS_NAME IN VARCHAR2, P_MESSAGE IN VARCHAR2, P_CLOB IN CLOB)

	AS

	PRAGMA AUTONOMOUS_TRANSACTION;

	BEGIN

		INSERT INTO OMS.ADM_LOG_CLOB (PACKAGE_NAME, PROCESS_NAME, MESSAGE, CDATA, CREATION_DATE, CREATED_BY)

		VALUES (P_PACKAGE_NAME, P_PROCESS_NAME, P_MESSAGE, P_CLOB, CURRENT_TIMESTAMP, USER);



		COMMIT;

	EXCEPTION

		WHEN OTHERS THEN NULL;

	END PR_INS_LOG_CLOB;



	-----



    PROCEDURE PR_LOAD_DETAILS(P_FULL_REFRESH IN CHAR DEFAULT 'N')

    AS

        v_root_url       VARCHAR2(2000);

        v_get_url        VARCHAR2(2000);

        v_get_api        VARCHAR2(100);

        --

        p_company_id     varchar2(2000) := 'c9225800-2b58-ec11-9f08-002248210987'; --Foods usa usd company



        v_insert_count   NUMBER;

        v_update_count   NUMBER := 0;

        v_exists         number := 0;

        v_company        varchar2(1000);

        v_count          NUMBER := 0;

        j                apex_json.t_values;



        v_systemid       varchar2(500);

        v_last_date      varchar2(100);

        v_next_date      varchar2(100);

        v_query          varchar2(1000);

        v_clob           clob;



      BEGIN

        GET_ENVIRONMENT(g_environment);



        v_get_api := AJC_BC_WS_UTILS_PKG.GET_API_F

            (

              p_entity => 'DETAILED CUSTOMER LEDGER ENTRIES'

            , p_subentity => NULL

            , p_method => 'GET'

            );



        FOR c_comp in

            (

            SELECT DISTINCT BC_COMPANY_ID, BC_COMPANY_NAME 

            FROM AJC.AJC_BC_COMPANIES

            WHERE ORACLE_COMPANY_NUMBER IN ('01','18','23') 

            )

        LOOP

            IF P_FULL_REFRESH = 'N' THEN

				BEGIN

					SELECT MAX(TO_CHAR( ( ( TO_TIMESTAMP_TZ(systemModifiedAt, 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"'))- INTERVAL '3' HOUR), 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"'))

						 , MAX(TO_CHAR( ( ( TO_TIMESTAMP_TZ(systemModifiedAt, 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"'))+ INTERVAL '90' day), 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"'))

					  INTO v_last_date

						 , v_next_date

					FROM AJC.BC_CLE_DETAIL

					WHERE BC_COMPANY_ID = c_comp.BC_COMPANY_ID;

					--

				EXCEPTION

					WHEN NO_DATA_FOUND THEN

						v_last_date := '2023-07-01T00:00:00.000Z';

						v_next_date := '2023-07-15T00:00:00.000Z';

				END;

				--

				IF v_last_date IS NULL OR v_next_date IS NULL THEN

					v_last_date := '2023-07-01T00:00:00.000Z';

					v_next_date := '2023-07-15T00:00:00.000Z';

				END IF;

			ELSIF P_FULL_REFRESH = 'Y' THEN

				v_last_date := '2023-07-01T00:00:00.000Z';

			END IF;

            --

            --v_last_date := '2023-07-01T00:00:00.000Z';

            --

            --v_query := '?$filter=systemModifiedAt%20ge%20'||v_last_date||'%20and%20systemModifiedAt%20le%20'||v_next_date||'&$schemaversion=1.0';

            --v_query := '?$filter=systemModifiedAt%20ge%20'||v_last_date||'&$orderby=systemModifiedAt%20asc&$schemaversion=1.0';

            v_query := '?$filter=systemModifiedAt%20ge%20'||v_last_date||'&$schemaversion=1.0';

            --

            v_root_url := ajc_bc_ws_utils_pkg.get_base_inecta_url_f ( g_environment, c_comp.bc_company_id ) || v_get_api;

            --

            LOOP

                v_get_url := v_root_url || v_query;

                -- 

                DBMS_OUTPUT.PUT_LINE(' DETAIL CLE, Next URL: ' || v_get_url);

                OMS.UTL_LOG.PR_INFO(g_execution_id, 'DETAIL CLE, Next URL: ' || v_get_url);

                --

                APEX_WEB_SERVICE.SET_REQUEST_HEADERS

				(

				  p_name_01        => 'Content-Type'

				, p_value_01       => 'application/json'

				);



                v_clob := APEX_WEB_SERVICE.MAKE_REST_REQUEST

				(

				  p_url => v_get_url

				, p_http_method => 'GET'

				, p_credential_static_id => g_credential_static_id

				, p_token_url => g_token_url

				);

                --

                apex_json.parse(j, v_clob);

                --

                v_count := apex_json.get_count(p_path=>'value',p_values=>j);

                --

                DBMS_OUTPUT.PUT_LINE(' COMPANY: '||c_comp.bc_company_name||' last_date: '||v_last_date||', URL: '||v_get_url);

                OMS.UTL_LOG.PR_INFO(g_execution_id, 'DETAIL CLE, Company: '||c_comp.bc_company_name||' last_date: '||v_last_date);

                --

                DBMS_OUTPUT.PUT_LINE(' result: '||APEX_WEB_SERVICE.G_REASON_PHRASE||', status: '||APEX_WEB_SERVICE.G_STATUS_CODE||', ROWS: '||v_count);

                OMS.UTL_LOG.PR_INFO(g_execution_id, 'DETAIL CLE, HTTP Response Phrase: '||APEX_WEB_SERVICE.G_REASON_PHRASE||', Status: '||APEX_WEB_SERVICE.G_STATUS_CODE||', Rows: '||v_count);

                --

                v_insert_count := 0;

                v_update_count := 0;

                v_company := c_comp.bc_company_name;

                --

                IF v_count > 0 THEN

                    BEGIN

					FOR cdclec IN 

					(

                        SELECT systemId,

                           amount,

                           amountLCY,

                           amountInCompanyCurrencyINE,

                           applicationNo,

                           appliedCustLedgerEntryNo,

                           companyCurrencyCodeINE,

                           creditAmount,

                           creditAmountLCY,

						   OMS.UTIL_INTEGRAT_BC_PKG.FN_GET_CCY_BC_TO_OG(p_bc_ccy => CURRENCYCODE) CURRENCYCODE, --https://ajcict.atlassian.net/browse/LOII-1745

                           --currencyCode,

                           custLedgerEntryNo,

                           customerNo,

                           debitAmount,

                           debitAmountLCY,

                           documentNo,

                           documentType,

                           entryNo,

                           entryType,

                           initialDocumentType,

                           initialEntryDueDate,

                           initialEntryGlobalDim1,

                           initialEntryGlobalDim2,

                           journalBatchName,

                           ledgerEntryAmount,

                           maxPaymentTolerance,

                           postingDate,

                           reasonCode,

                           remainingPmtDiscPossible,

                           sourceCode,

                           systemCreatedAt,

                           systemCreatedBy,

                           systemModifiedAt,

                           systemModifiedBy,

                           taxJurisdictionCode,

                           transactionNo,

                           unapplied,

                           unappliedByEntryNo,

                           useTax,

                           userID,

                           createdDate,

                           createdTime,

                           modifiedDate,

                           modifiedTime,

                           'NEW' status, 

                           TRUNC(SYSDATE) creation_date,

                           null request_id

                      FROM json_table

					  ( v_clob, '$.value[*]' 

						COLUMNS 

						( systemId                     VARCHAR2(4000) path '$.systemId',

						  amount                       VARCHAR2(4000) path '$.amount',

						  amountLCY                    VARCHAR2(4000) path '$.amountLCY',

						  amountInCompanyCurrencyINE   VARCHAR2(4000) path '$.amountInCompanyCurrencyINE',

						  applicationNo                VARCHAR2(4000) path '$.applicationNo',

						  appliedCustLedgerEntryNo     VARCHAR2(4000) path '$.appliedCustLedgerEntryNo',

						  companyCurrencyCodeINE       VARCHAR2(4000) path '$.companyCurrencyCodeINE',

						  creditAmount                 VARCHAR2(4000) path '$.creditAmount',

						  creditAmountLCY              VARCHAR2(4000) path '$.creditAmountLCY',

						  currencyCode                 VARCHAR2(4000) path '$.currencyCode',

						  custLedgerEntryNo            VARCHAR2(4000) path '$.custLedgerEntryNo',

						  customerNo                   VARCHAR2(4000) path '$.customerNo',

						  debitAmount                  VARCHAR2(4000) path '$.debitAmount',

						  debitAmountLCY               VARCHAR2(4000) path '$.debitAmountLCY',

						  documentNo                   VARCHAR2(4000) path '$.documentNo',

						  documentType                 VARCHAR2(4000) path '$.documentType',

						  entryNo                      VARCHAR2(4000) path '$.entryNo',

						  entryType                    VARCHAR2(4000) path '$.entryType',

						  initialDocumentType          VARCHAR2(4000) path '$.initialDocumentType',

						  initialEntryDueDate          VARCHAR2(4000) path '$.initialEntryDueDate',

						  initialEntryGlobalDim1       VARCHAR2(4000) path '$.initialEntryGlobalDim1',

						  initialEntryGlobalDim2       VARCHAR2(4000) path '$.initialEntryGlobalDim2',

						  journalBatchName             VARCHAR2(4000) path '$.journalBatchName',

						  ledgerEntryAmount            VARCHAR2(4000) path '$.ledgerEntryAmount',

						  maxPaymentTolerance          VARCHAR2(4000) path '$.maxPaymentTolerance',

						  postingDate                  VARCHAR2(4000) path '$.postingDate',

						  reasonCode                   VARCHAR2(4000) path '$.reasonCode',

						  remainingPmtDiscPossible     VARCHAR2(4000) path '$.remainingPmtDiscPossible',

						  sourceCode                   VARCHAR2(4000) path '$.sourceCode',

						  systemCreatedAt              VARCHAR2(4000) path '$.systemCreatedAt',

						  systemCreatedBy              VARCHAR2(4000) path '$.systemCreatedBy',

						  systemModifiedAt             VARCHAR2(4000) path '$.systemModifiedAt',

						  systemModifiedBy             VARCHAR2(4000) path '$.systemModifiedBy',

						  taxJurisdictionCode          VARCHAR2(4000) path '$.taxJurisdictionCode',

						  transactionNo                VARCHAR2(4000) path '$.transactionNo',

						  unapplied                    VARCHAR2(4000) path '$.unapplied',

						  unappliedByEntryNo           VARCHAR2(4000) path '$.unappliedByEntryNo',

						  useTax                       VARCHAR2(4000) path '$.useTax',

						  userID                       VARCHAR2(4000) path '$.userID',

						  createdDate                  VARCHAR2(4000) path '$.createdDate',

						  createdTime                  VARCHAR2(4000) path '$.createdTime',

						  modifiedDate                 VARCHAR2(4000) path '$.modifiedDate',

						  modifiedTime                 VARCHAR2(4000) path '$.modifiedTime' 

						)

					  )

					  where initialEntryGlobalDim1 in ('01','18','23') 

                    )

                    LOOP



                        SELECT COUNT(*) 

                        INTO v_exists

                        FROM ajc.BC_CLE_DETAIL

                        WHERE entryno = cdclec.entryno

                        AND bc_company_id = c_comp.bc_company_id

                        ;



                        v_systemid := cdclec.entryno;



                        --dbms_output.put_line('v_exists: '||v_exists||' SYSTEMID: '||v_systemid);



                        IF v_exists = 0 THEN

                            INSERT

                            INTO ajc.BC_CLE_DETAIL

                               ( systemId,

                                 amount,

                                 amountLCY,

                                 amountInCompanyCurrencyINE,

                                 applicationNo,

                                 appliedCustLedgerEntryNo,

                                 companyCurrencyCodeINE,

                                 creditAmount,

                                 creditAmountLCY,

                                 currencyCode,

                                 custLedgerEntryNo,

                                 customerNo,

                                 debitAmount,

                                 debitAmountLCY,

                                 documentNo,

                                 documentType,

                                 entryNo,

                                 entryType,

                                 initialDocumentType,

                                 initialEntryDueDate,

                                 initialEntryGlobalDim1,

                                 initialEntryGlobalDim2,

                                 journalBatchName,

                                 ledgerEntryAmount,

                                 maxPaymentTolerance,

                                 postingDate,

                                 reasonCode,

                                 remainingPmtDiscPossible,

                                 sourceCode,

                                 systemCreatedAt,

                                 systemCreatedBy,

                                 systemModifiedAt,

                                 systemModifiedBy,

                                 taxJurisdictionCode,

                                 transactionNo,

                                 unapplied,

                                 unappliedByEntryNo,

                                 useTax,

                                 userID,

                                 createdDate,

                                 createdTime,

                                 modifiedDate,

                                 modifiedTime,

                                 status, 

                                 creation_date,

                                 request_id,

                                 bc_environment,

                                 trx_number,

                                 bc_company_id)

                            VALUES ( cdclec.systemId,

                                 cdclec.amount,

                                 cdclec.amountLCY,

                                 cdclec.amountInCompanyCurrencyINE,

                                 cdclec.applicationNo,

                                 cdclec.appliedCustLedgerEntryNo,

                                 cdclec.companyCurrencyCodeINE,

                                 cdclec.creditAmount,

                                 cdclec.creditAmountLCY,

                                 cdclec.currencyCode,

                                 cdclec.custLedgerEntryNo,

                                 cdclec.customerNo,

                                 cdclec.debitAmount,

                                 cdclec.debitAmountLCY,

                                 cdclec.documentNo,

                                 cdclec.documentType,

                                 cdclec.entryNo,

                                 cdclec.entryType,

                                 cdclec.initialDocumentType,

                                 cdclec.initialEntryDueDate,

                                 cdclec.initialEntryGlobalDim1,

                                 cdclec.initialEntryGlobalDim2,

                                 cdclec.journalBatchName,

                                 cdclec.ledgerEntryAmount,

                                 cdclec.maxPaymentTolerance,

                                 cdclec.postingDate,

                                 cdclec.reasonCode,

                                 cdclec.remainingPmtDiscPossible,

                                 cdclec.sourceCode,

                                 cdclec.systemCreatedAt,

                                 cdclec.systemCreatedBy,

                                 cdclec.systemModifiedAt,

                                 cdclec.systemModifiedBy,

                                 cdclec.taxJurisdictionCode,

                                 cdclec.transactionNo,

                                 cdclec.unapplied,

                                 cdclec.unappliedByEntryNo,

                                 cdclec.useTax,

                                 cdclec.userID,

                                 cdclec.createdDate,

                                 cdclec.createdTime,

                                 cdclec.modifiedDate,

                                 cdclec.modifiedTime,

                                 cdclec.status, 

                                 cdclec.creation_date,

                                 cdclec.request_id,

                                 g_environment,

                                 DECODE(SUBSTR(cdclec.documentNo,1,3),'AR-',SUBSTR(cdclec.documentNo,4),cdclec.documentNo),

                                 c_comp.bc_company_id

                                 );



                                 v_insert_count := v_insert_count + 1;

                        else

                            UPDATE ajc.BC_CLE_DETAIL

                                SET systemId = cdclec.systemId,

                                 amount = cdclec.amount,

                                 amountLCY = cdclec.amountLCY,

                                 amountInCompanyCurrencyINE = cdclec.amountInCompanyCurrencyINE,

                                 applicationNo = cdclec.applicationNo,

                                 appliedCustLedgerEntryNo = cdclec.appliedCustLedgerEntryNo,

                                 companyCurrencyCodeINE = cdclec.companyCurrencyCodeINE,

                                 creditAmount = cdclec.creditAmount,

                                 creditAmountLCY = cdclec.creditAmountLCY,

                                 currencyCode = cdclec.currencyCode,

                                 custLedgerEntryNo =  cdclec.custLedgerEntryNo,

                                 customerNo = cdclec.customerNo,

                                 debitAmount = cdclec.debitAmount,

                                 debitAmountLCY = cdclec.debitAmountLCY,

                                 documentNo = cdclec.documentNo,

                                 documentType = cdclec.documentType,

                                 entryNo = cdclec.entryNo,

                                 entryType = cdclec.entryType,

                                 initialDocumentType = cdclec.initialDocumentType,

                                 initialEntryDueDate = cdclec.initialEntryDueDate,

                                 initialEntryGlobalDim1 = cdclec.initialEntryGlobalDim1,

                                 initialEntryGlobalDim2 = cdclec.initialEntryGlobalDim2, 

                                 journalBatchName = cdclec.journalBatchName,

                                 ledgerEntryAmount = cdclec.ledgerEntryAmount,

                                 maxPaymentTolerance = cdclec.maxPaymentTolerance,

                                 postingDate = cdclec.postingDate,

                                 reasonCode = cdclec.reasonCode,

                                 remainingPmtDiscPossible = cdclec.remainingPmtDiscPossible,

                                 sourceCode = cdclec.sourceCode,

                                 systemCreatedAt = cdclec.systemCreatedAt,

                                 systemCreatedBy = cdclec.systemCreatedBy,

                                 systemModifiedAt = cdclec.systemModifiedAt,

                                 systemModifiedBy = cdclec.systemModifiedBy,

                                 taxJurisdictionCode = cdclec.taxJurisdictionCode,

                                 transactionNo = cdclec.transactionNo,

                                 unapplied = cdclec.unapplied,

                                 unappliedByEntryNo = cdclec.unappliedByEntryNo,

                                 useTax = cdclec.useTax,

                                 userID = cdclec.userID,

                                 createdDate = cdclec.createdDate,

                                 createdTime = cdclec.createdTime,

                                 modifiedDate = cdclec.modifiedDate,

                                 modifiedTime = cdclec.modifiedTime,

                                 status = cdclec.status, 

                                 creation_date = cdclec.creation_date,

                                 request_id = cdclec.request_id,

                                 trx_number = DECODE(SUBSTR(cdclec.documentNo,1,3),'AR-',SUBSTR(cdclec.documentNo,4),cdclec.documentNo) 

                                 --bc_company_id = c_comp.bc_company_id

                            WHERE entryno = cdclec.entryno 

                            and bc_company_id = c_comp.bc_company_id;



                            v_update_count := v_update_count + 1;

                        end if;

                        --

                        /* Flags the header for post-processing */

                        UPDATE AJC.BC_CLE_HEADER

                           SET POST_PROCESSED = 0

                        WHERE entryNo = cdclec.custLedgerEntryNo 

                          AND bc_company_id = c_comp.bc_company_id;

                        --

					END LOOP;

					EXCEPTION

						WHEN OTHERS THEN

							PR_INS_LOG_CLOB(P_PACKAGE_NAME => CONST_PACKAGE_NAME, 

											P_PROCESS_NAME => 'PR_LOAD_DETAILS', 

											P_MESSAGE => 'DETAIL CLE, Unexpected Error: '||SQLCODE||'-'||SQLERRM

														||'(Context: SystemID: ' || v_systemid||', Company: '||v_company||', last_date: '||v_last_date

														||' Trace: '||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, 

											P_CLOB => v_clob);

					END;

                END IF; --IF v_count > 0 THEN

                --

                DBMS_OUTPUT.PUT_LINE(' DETAIL CLE, Rows inserted: ' || V_INSERT_COUNT ||', updated: '||V_UPDATE_COUNT );

                OMS.UTL_LOG.PR_INFO(g_execution_id, 'DETAIL CLE, Rows inserted: ' || V_INSERT_COUNT ||', updated: '||V_UPDATE_COUNT );

                --

                COMMIT;

                --

                BEGIN

                    SELECT SUBSTR(NEXT_URL, INSTR(NEXT_URL, '?'))

                      INTO v_query

                    FROM JSON_TABLE

                        (

                        REPLACE(v_clob, '@', ''), '$'

                        COLUMNS

                            (

                            NEXT_URL VARCHAR2(4000) PATH '$."odata.nextLink"'

                            )

                        );

                    --

                EXCEPTION

                    WHEN NO_DATA_FOUND THEN

                        NULL;

                END;

                --

                EXIT WHEN v_query IS NULL;

                --

                IF v_query IS NOT NULL THEN

                    DBMS_OUTPUT.PUT_LINE(' DETAIL CLE, Next Query String: ' || v_query);

                END IF;

                --

            END LOOP;

        END LOOP;

        --

    EXCEPTION

        WHEN OTHERS THEN

            RAISE_APPLICATION_ERROR

                (

                  -20001

                , 'DETAIL CLE, Unexpected Error: '||SQLCODE||'-'||SQLERRM

                ||'(Context: SystemID: ' || v_systemid||', Company: '||v_company||', last_date: '||v_last_date||')'

                );

    END PR_LOAD_DETAILS;



    ------



    PROCEDURE PR_LOAD_HEADERS (P_FULL_REFRESH IN CHAR DEFAULT 'N')

    AS

        v_root_url       VARCHAR2(2000);

        v_get_url        VARCHAR2(2000);

        v_get_api        VARCHAR2(100);

        --

        v_insert_count   NUMBER;

        v_update_count   NUMBER := 0;

        v_exists         number := 0;

        v_count          NUMBER := 0;

        j                apex_json.t_values;

        v_systemid       varchar2(500);

        v_company        varchar2(100);

        v_last_date      varchar2(100);

        v_next_date      varchar2(100);

        v_query          varchar2(1000);

        p_company_id     varchar2(2000) := 'c9225800-2b58-ec11-9f08-002248210987'; --Foods usa usd company

        v_clob           CLOB;

        --

        v_tk_org_company COMPANY.TK_ORG%TYPE;

        v_customer_id    RA_CUSTOMERS.CUSTOMER_ID%TYPE;

        v_tk_invoice     OMS.OG_INVOICE.TK_INVOICE%TYPE;

		v_tk_lo          OMS.OG_INVOICE.TK_LO%TYPE;

        --

     BEGIN

        GET_ENVIRONMENT(g_environment);

        --

        v_get_api := ajc_bc_ws_utils_pkg.get_api_f

            (

              p_entity => 'CUSTOMER LEDGER ENTRIES'

            , p_subentity => NULL

            , p_method => 'GET'

            );                                         



        FOR c_comp IN 

            (

            SELECT DISTINCT BC_COMPANY_ID, BC_COMPANY_NAME 

            FROM AJC.AJC_BC_COMPANIES

            WHERE ORACLE_COMPANY_NUMBER IN ('01','18','23') 

            )

        LOOP

            IF P_FULL_REFRESH = 'N' THEN

				BEGIN

					SELECT MAX(TO_CHAR( ( ( TO_TIMESTAMP_TZ(systemModifiedAt, 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"'))- INTERVAL '3' HOUR), 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"'))

						 , MAX(TO_CHAR( ( ( TO_TIMESTAMP_TZ(systemModifiedAt, 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"'))+ INTERVAL '90' day), 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"'))

					  INTO v_last_date

						 , v_next_date

					FROM AJC.BC_CLE_HEADER

					WHERE BC_COMPANY_ID = c_comp.BC_COMPANY_ID;

					--

				EXCEPTION

					WHEN NO_DATA_FOUND THEN

						v_last_date := '2023-07-01T00:00:00.000Z';

						v_next_date := '2023-07-105T00:00:00.000Z';

				END;

				--

				IF v_last_date IS NULL OR v_next_date IS NULL THEN

					v_last_date := '2023-07-01T00:00:00.000Z';

					v_next_date := '2023-07-15T00:00:00.000Z';

				END IF;

			ELSIF P_FULL_REFRESH = 'Y' THEN

				v_last_date := '2023-07-01T00:00:00.000Z';

			END IF;

            --

            --v_last_date := '2023-07-01T00:00:00.000Z';

            --

            --v_query := '?$filter=systemModifiedAt%20ge%20'||v_last_date||'&$schemaversion=1.0';

            --v_query := '?$filter=systemModifiedAt%20ge%20'||v_last_date||'%20and%20systemModifiedAt%20le%20'||v_next_date||'&$schemaversion=1.0';

            --v_query := '?$filter=systemModifiedAt%20ge%20'||v_last_date||'&$orderby=systemModifiedAt%20asc&$schemaversion=1.0';

            v_query := '?$filter=systemModifiedAt%20ge%20'||v_last_date||'&$schemaversion=1.0';

            --

            v_root_url := AJC_BC_WS_UTILS_PKG.GET_BASE_INECTA_URL_F( g_environment, c_comp.bc_company_id ) || v_get_api;

            --

            LOOP

                v_get_url := v_root_url || v_query;

                -- 

                DBMS_OUTPUT.PUT_LINE(' HEADER CLE, Next URL: '||v_get_url);

                OMS.UTL_LOG.PR_INFO(g_execution_id, 'HEADER CLE, Next URL: ' || v_get_url);

                --        

                APEX_WEB_SERVICE.SET_REQUEST_HEADERS

                    (

                      p_name_01  => 'Content-Type'

                    , p_value_01 => 'application/json'

                    );

                --

                v_clob := APEX_WEB_SERVICE.MAKE_REST_REQUEST

                    (

                      p_url => v_get_url 

                    , p_http_method => 'GET'

                    , p_credential_static_id => g_credential_static_id

                    , p_token_url => g_token_url

                    );

                --

                APEX_JSON.PARSE(j, v_clob);

                -- 

                v_count := APEX_JSON.GET_COUNT(p_path=>'value', p_values=>j);

                --

                DBMS_OUTPUT.PUT_LINE(' COMPANY: '||c_comp.bc_company_name||' last_date: '||v_last_date||', URL: '||v_get_url);

                OMS.UTL_LOG.PR_INFO(g_execution_id, 'HEADER CLE, Company: '||c_comp.bc_company_name||' last_date: '||v_last_date);

                --

                DBMS_OUTPUT.PUT_LINE(' Result: '||APEX_WEB_SERVICE.G_REASON_PHRASE||', status: '||APEX_WEB_SERVICE.G_STATUS_CODE||', ROWS: '||v_count);

                OMS.UTL_LOG.PR_INFO(g_execution_id, 'HEADER CLE, HTTP Response Phrase: '||APEX_WEB_SERVICE.G_REASON_PHRASE||', Status: '||APEX_WEB_SERVICE.G_STATUS_CODE||', Rows: '||v_count);

                --

                v_insert_count := 0;

                v_update_count := 0;

                v_company := c_comp.bc_company_name;

                --

                IF v_count > 0 THEN

                    BEGIN

					FOR cclec IN 

					(

                        SELECT systemId,

                           adjustedCurrencyFactor,

                           amount,

                           amountLCY,

                           appliesToDocNo,

                           -- 20240617 appliesToDocType,

                           appliesToDocType,

                           -- 20240617

                           appliesToExtDocNo,

                           balAccountNo,

                           -- 20240617 balAccountType,

                           balAccountType,

                           -- 20240617

                           DECODE(closedAtDate,'0001-01-01',NULL,closedAtDate) closedAtDate ,

                           closedByAmount,

                           closedByAmountLCY,

                           closedByCurrencyAmount,

                           closedByEntryNo,

                           creditAmount,

                           creditAmountLCY,

						   OMS.UTIL_INTEGRAT_BC_PKG.FN_GET_CCY_BC_TO_OG(p_bc_ccy => CURRENCYCODE) CURRENCYCODE, --https://ajcict.atlassian.net/browse/LOII-1745

                           --currencyCode,

                           customerName,

                           customerNo,

                           debitAmount,

                           debitAmountLCY,

                           description,

                           documentDate,

                           documentNo,

                           -- 20240617 documentType,

                           documentType,

                           -- 20240617

                           dueDate,

                           comments,

                           entryNo,

                           globalDimension1Code,

                           globalDimension2Code,

                           journalBatchName,

                           originalAmount,

                           originalAmtLCY,

                           originalCurrencyFactor,

                           postingDate,

                           prepayment,

                           remainingAmount,

                           remainingAmtLCY,

                           reversed,

                           salesLCY,

                           sellToCustomerNo,

                           shortcutDimension3Code,

                           shortcutDimension4Code,

                           shortcutDimension5Code,

                           shortcutDimension6Code,

                           shortcutDimension7Code,

                           --shortcutDimension8Code,

                           REPLACE(shortcutDimension8Code,'SO','') shortcutDimension8Code,

                           sourceCode,

                           creditMemoAdjustment,

                           paymentTermsCode,

                           systemCreatedAt,

                           systemCreatedBy,

                           systemModifiedAt,

                           systemModifiedBy,

                           transactionNo,

                           userID,

                           createdDate,

                           createdTime,

                           modifiedDate,

                           modifiedTime,

                           'NEW' status, 

                           TRUNC(SYSDATE) creation_date,

                           null request_id

                      FROM json_table

					  ( v_clob, '$.value[*]' 

						COLUMNS 

							( systemId                 VARCHAR2(4000) path '$.systemId',

							  adjustedCurrencyFactor   VARCHAR2(4000) path '$.adjustedCurrencyFactor',

							  amount                   VARCHAR2(4000) path '$.amount',

							  amountLCY                VARCHAR2(4000) path '$.amountLCY',

							  appliesToDocNo           VARCHAR2(4000) path '$.appliesToDocNo',

							  appliesToDocType         VARCHAR2(4000) path '$.appliesToDocType',

							  appliesToExtDocNo        VARCHAR2(4000) path '$.appliesToExtDocNo',

							  balAccountNo             VARCHAR2(4000) path '$.balAccountNo',

							  balAccountType           VARCHAR2(4000) path '$.balAccountType',

							  closedAtDate             VARCHAR2(4000) path '$.closedAtDate',

							  closedByAmount           VARCHAR2(4000) path '$.closedByAmount',

							  closedByAmountLCY        VARCHAR2(4000) path '$.closedByAmountLCY',

							  closedByCurrencyAmount   VARCHAR2(4000) path '$.closedByCurrencyAmount',

							  closedByEntryNo          VARCHAR2(4000) path '$.closedByEntryNo',

							  creditAmount             VARCHAR2(4000) path '$.creditAmount',

							  creditAmountLCY          VARCHAR2(4000) path '$.creditAmountLCY',

							  currencyCode             VARCHAR2(4000) path '$.currencyCode',

							  customerName             VARCHAR2(4000) path '$.customerName',

							  customerNo               VARCHAR2(4000) path '$.customerNo',

							  debitAmount              VARCHAR2(4000) path '$.debitAmount',

							  debitAmountLCY           VARCHAR2(4000) path '$.debitAmountLCY',

							  description              VARCHAR2(4000) path '$.description',

							  documentDate             VARCHAR2(4000) path '$.documentDate',

							  documentNo               VARCHAR2(4000) path '$.documentNo',

							  documentType             VARCHAR2(4000) path '$.documentType',

							  dueDate                  VARCHAR2(4000) path '$.dueDate',

							  comments                 VARCHAR2(4000) path '$.comment',

							  entryNo                  VARCHAR2(4000) path '$.entryNo',

							  globalDimension1Code     VARCHAR2(4000) path '$.globalDimension1Code',

							  globalDimension2Code     VARCHAR2(4000) path '$.globalDimension2Code',

							  journalBatchName         VARCHAR2(4000) path '$.journalBatchName',

							  originalAmount           VARCHAR2(4000) path '$.originalAmount',

							  originalAmtLCY           VARCHAR2(4000) path '$.originalAmtLCY',

							  originalCurrencyFactor   VARCHAR2(4000) path '$.originalCurrencyFactor',

							  postingDate              VARCHAR2(4000) path '$.postingDate',

							  prepayment               VARCHAR2(4000) path '$.prepayment',

							  remainingAmount          VARCHAR2(4000) path '$.remainingAmount',

							  remainingAmtLCY          VARCHAR2(4000) path '$.remainingAmtLCY',

							  reversed                 VARCHAR2(4000) path '$.reversed',

							  salesLCY                 VARCHAR2(4000) path '$.salesLCY',

							  sellToCustomerNo         VARCHAR2(4000) path '$.sellToCustomerNo',

							  shortcutDimension3Code   VARCHAR2(4000) path '$.shortcutDimension3Code',

							  shortcutDimension4Code   VARCHAR2(4000) path '$.shortcutDimension4Code',

							  shortcutDimension5Code   VARCHAR2(4000) path '$.shortcutDimension5Code',

							  shortcutDimension6Code   VARCHAR2(4000) path '$.shortcutDimension6Code',

							  shortcutDimension7Code   VARCHAR2(4000) path '$.shortcutDimension7Code',

							  shortcutDimension8Code   VARCHAR2(4000) path '$.shortcutDimension8Code',

							  sourceCode               VARCHAR2(4000) path '$.sourceCode',

							  creditMemoAdjustment     VARCHAR2(4000) path '$.creditMemoAdjustment',

							  paymentTermsCode         VARCHAR2(4000) path '$.paymentTermsCode',

							  systemCreatedAt          VARCHAR2(4000) path '$.systemCreatedAt',

							  systemCreatedBy          VARCHAR2(4000) path '$.systemCreatedBy',

							  systemModifiedAt         VARCHAR2(4000) path '$.systemModifiedAt',

							  systemModifiedBy         VARCHAR2(4000) path '$.systemModifiedBy',

							  transactionNo            VARCHAR2(4000) path '$.transactionNo',

							  userID                   VARCHAR2(4000) path '$.userID',

							  createdDate              VARCHAR2(4000) path '$.createdDate',

							  createdTime              VARCHAR2(4000) path '$.createdTime',

							  modifiedDate             VARCHAR2(4000) path '$.modifiedDate',

							  modifiedTime             VARCHAR2(4000) path '$.modifiedTime' 

							)

						)

						where globalDimension1Code in ('01','18','23')

                    )

                    LOOP

                        SELECT COUNT(*) 

                        INTO v_exists

                        FROM ajc.BC_CLE_HEADER

                        WHERE entryNo = cclec.entryNo

                        and bc_company_id = c_comp.bc_company_id

                        ;



                        v_systemid := cclec.entryNo;



                        -- Getting the TK_ORG_COMPANY using the globalDimension1Code from the AJC.BC_COMPANY View

                        <<get_tk_org_company>>

                        BEGIN

                            SELECT CO.TK_ORG_COMPANY

                              INTO v_tk_org_company

                            FROM AJC.BC_COMPANY CO

                            WHERE 1 = 1

                              AND CO.COMPANY_CODE   = cclec.globalDimension1Code;

                            --

                        EXCEPTION

                            WHEN OTHERS THEN

                                v_tk_org_company := NULL;

                        END get_tk_org_company;



                        -- Getting the Customer ID using the Customer Number

                        <<get_customer_id>>

                        BEGIN

                            SELECT CUSTOMER_ID

                            INTO v_customer_id

                            FROM RA_CUSTOMERS

                            WHERE CUSTOMER_NUMBER = cclec.customerNo;

                        EXCEPTION

                            WHEN OTHERS THEN

                                v_customer_id := NULL;

                        END get_customer_id;



                        -- Getting the TK_INVOICE using the DocumentNo and Company from the oms.OG_INVOICE Table

                        <<get_tk_invoice>>

                        BEGIN

							SELECT OG.TK_INVOICE, OG.TK_LO

                              INTO v_tk_invoice, v_tk_lo

                            FROM OMS.OG_INVOICE OG

                            WHERE 1 = 1

                              AND OG.INVOICE_NUMBER = DECODE(SUBSTR(cclec.documentNo,1,3),'AR-',SUBSTR(cclec.documentNo,4),cclec.documentNo)

                              AND OG.TK_ORG_COMPANY = v_tk_org_company;

                            --

                        EXCEPTION

                            WHEN OTHERS THEN

                                v_tk_invoice := NULL;

                        END get_tk_invoice;



                        --dbms_output.put_line('v_systemid: '||v_systemid||', v_exists: '||v_exists);



                        IF v_exists = 0 THEN



                            INSERT

                            INTO ajc.BC_CLE_HEADER

                               ( systemId,

                                 adjustedCurrencyFactor,

                                 amount,

                                 amountLCY,

                                 appliesToDocNo,

                                 appliesToDocType,

                                 appliesToExtDocNo,

                                 balAccountNo,

                                 balAccountType,

                                 closedAtDate,

                                 closedByAmount,

                                 closedByAmountLCY,

                                 closedByCurrencyAmount,

                                 closedByEntryNo,

                                 creditAmount,

                                 creditAmountLCY,

                                 currencyCode,

                                 customerName,

                                 customerNo,

                                 customer_id,

                                 debitAmount,

                                 debitAmountLCY,

                                 description,

                                 documentDate,

                                 documentNo,

                                 documentType,

                                 dueDate,

                                 comments,

                                 entryNo,

                                 globalDimension1Code,

                                 globalDimension2Code,

                                 journalBatchName,

                                 originalAmount,

                                 originalAmtLCY,

                                 originalCurrencyFactor,

                                 postingDate,

                                 prepayment,

                                 remainingAmount,

                                 remainingAmtLCY,

                                 reversed,

                                 salesLCY,

                                 sellToCustomerNo,

                                 shortcutDimension3Code,

                                 shortcutDimension4Code,

                                 shortcutDimension5Code,

                                 shortcutDimension6Code,

                                 shortcutDimension7Code,

                                 shortcutDimension8Code,

                                 sourceCode,

                                 creditMemoAdjustment,

                                 paymentTermsCode,

                                 systemCreatedAt,

                                 systemCreatedBy,

                                 systemModifiedAt,

                                 systemModifiedBy,

                                 transactionNo,

                                 userID,

                                 createdDate,

                                 createdTime,

                                 modifiedDate,

                                 modifiedTime,

                                 status,

                                 creation_date,

                                 request_id,

                                 bc_environment,

                                 trx_number,

                                 bc_company_id,

                                 tk_invoice,

                                 tk_org_company,

								 tk_lo

                                 )

                            VALUES ( cclec.systemId,

                                 cclec.adjustedCurrencyFactor,

                                 cclec.amount,

                                 cclec.amountLCY,

                                 cclec.appliesToDocNo,

                                 cclec.appliesToDocType,

                                 cclec.appliesToExtDocNo,

                                 cclec.balAccountNo,

                                 cclec.balAccountType,

                                 cclec.closedAtDate,

                                 cclec.closedByAmount,

                                 cclec.closedByAmountLCY,

                                 cclec.closedByCurrencyAmount,

                                 cclec.closedByEntryNo,

                                 cclec.creditAmount,

                                 cclec.creditAmountLCY,

                                 cclec.currencyCode,

                                 cclec.customerName,

                                 cclec.customerNo,

                                 v_customer_id,

                                 cclec.debitAmount,

                                 cclec.debitAmountLCY,

                                 cclec.description,

                                 cclec.documentDate,

                                 cclec.documentNo,

                                 cclec.documentType,

                                 cclec.dueDate,

                                 cclec.comments,

                                 cclec.entryNo,

                                 cclec.globalDimension1Code,

                                 cclec.globalDimension2Code,

                                 cclec.journalBatchName,

                                 cclec.originalAmount,

                                 cclec.originalAmtLCY,

                                 cclec.originalCurrencyFactor,

                                 cclec.postingDate,

                                 cclec.prepayment,

                                 cclec.remainingAmount,

                                 cclec.remainingAmtLCY,

                                 cclec.reversed,

                                 cclec.salesLCY,

                                 cclec.sellToCustomerNo,

                                 cclec.shortcutDimension3Code,

                                 cclec.shortcutDimension4Code,

                                 cclec.shortcutDimension5Code,

                                 cclec.shortcutDimension6Code,

                                 cclec.shortcutDimension7Code,

                                 cclec.shortcutDimension8Code,

                                 cclec.sourceCode,

                                 cclec.creditMemoAdjustment,

                                 cclec.paymentTermsCode,

                                 cclec.systemCreatedAt,

                                 cclec.systemCreatedBy,

                                 cclec.systemModifiedAt,

                                 cclec.systemModifiedBy,

                                 cclec.transactionNo,

                                 cclec.userID,

                                 cclec.createdDate,

                                 cclec.createdTime,

                                 cclec.modifiedDate,

                                 cclec.modifiedTime,

                                 cclec.status, 

                                 cclec.creation_date,

                                 cclec.request_id,

                                 g_environment,

                                 DECODE(SUBSTR(cclec.documentNo,1,3),'AR-',SUBSTR(cclec.documentNo,4),cclec.documentNo) ,

                                 c_comp.bc_company_id,

                                 v_tk_invoice,

                                 v_tk_org_company,

								 v_tk_lo

                            );



                            v_insert_count := v_insert_count + 1;

                        else

                            UPDATE ajc.BC_CLE_HEADER

                                SET systemId = cclec.systemId,

                                 adjustedCurrencyFactor = cclec.adjustedCurrencyFactor,

                                 amount = cclec.amount,

                                 amountLCY = cclec.amountLCY,

                                 appliesToDocNo = cclec.appliesToDocNo,

                                 appliesToDocType = cclec.appliesToDocType,

                                 appliesToExtDocNo = cclec.appliesToExtDocNo,

                                 balAccountNo= cclec.balAccountNo,

                                 balAccountType = cclec.balAccountType,

                                 closedAtDate = cclec.closedAtDate,

                                 closedByAmount = cclec.closedByAmount,

                                 closedByAmountLCY = cclec.closedByAmountLCY,

                                 closedByCurrencyAmount = cclec.closedByCurrencyAmount,

                                 closedByEntryNo = cclec.closedByEntryNo,

                                 creditAmount = cclec.creditAmount,

                                 creditAmountLCY = cclec.creditAmountLCY,

                                 currencyCode = cclec.currencyCode,

                                 customerName = cclec.customerName,

                                 customerNo = cclec.customerNo,

                                 customer_id = v_customer_id,

                                 debitAmount = cclec.debitAmount,

                                 debitAmountLCY = cclec.debitAmountLCY,

                                 description = cclec.description,

                                 documentDate = cclec.documentDate,

                                 documentNo = cclec.documentNo,

                                 documentType = cclec.documentType,

                                 dueDate = cclec.dueDate,

                                 comments = cclec.comments,

                                 entryNo = cclec.entryNo,

                                 globalDimension1Code = cclec.globalDimension1Code,

                                 globalDimension2Code = cclec.globalDimension2Code,

                                 journalBatchName = cclec.journalBatchName,

                                 originalAmount = cclec.originalAmount,

                                 originalAmtLCY = cclec.originalAmtLCY,

                                 originalCurrencyFactor = cclec.originalCurrencyFactor,

                                 postingDate = cclec.postingDate,

                                 prepayment = cclec.prepayment,

                                 remainingAmount = cclec.remainingAmount,

                                 remainingAmtLCY = cclec.remainingAmtLCY,

                                 reversed = cclec.reversed,

                                 salesLCY = cclec.salesLCY,

                                 sellToCustomerNo = cclec.sellToCustomerNo,

                                 shortcutDimension3Code = cclec.shortcutDimension3Code,

                                 shortcutDimension4Code = cclec.shortcutDimension4Code,

                                 shortcutDimension5Code = cclec.shortcutDimension5Code,

                                 shortcutDimension6Code = cclec.shortcutDimension6Code,

                                 shortcutDimension7Code = cclec.shortcutDimension7Code,

                                 shortcutDimension8Code = cclec.shortcutDimension8Code,

                                 sourceCode = cclec.sourceCode,

                                 creditMemoAdjustment = cclec.creditMemoAdjustment,

                                 paymentTermsCode = cclec.paymentTermsCode,

                                 systemCreatedAt = cclec.systemCreatedAt,

                                 systemCreatedBy = cclec.systemCreatedBy,

                                 systemModifiedAt = cclec.systemModifiedAt,

                                 systemModifiedBy = cclec.systemModifiedBy,

                                 transactionNo = cclec.transactionNo,

                                 userID = cclec.userID,

                                 createdDate = cclec.createdDate,

                                 createdTime = cclec.createdTime,

                                 modifiedDate = cclec.modifiedDate,

                                 modifiedTime = cclec.modifiedTime,

                                 status = cclec.status, 

                                 creation_date = cclec.creation_date,

                                 request_id = cclec.request_id,

                                 trx_number = DECODE(SUBSTR(cclec.documentNo,1,3),'AR-',SUBSTR(cclec.documentNo,4),cclec.documentNo),

                                 tk_invoice = v_tk_invoice,

                                 tk_org_company = v_tk_org_company,

								 tk_lo = v_tk_lo,

								 post_processed = 0

                                 --bc_company_id = c_comp.bc_company_id

                            WHERE entryNo = cclec.entryNo 

                            and bc_company_id = c_comp.bc_company_id;



                            v_update_count := v_update_count + 1;

                        end if;



                    END LOOP;

					EXCEPTION

						WHEN OTHERS THEN

							PR_INS_LOG_CLOB(P_PACKAGE_NAME => CONST_PACKAGE_NAME, 

											P_PROCESS_NAME => 'PR_LOAD_HEADERS', 

											P_MESSAGE => 'DETAIL CLE, Unexpected Error: '||SQLCODE||'-'||SQLERRM

														||'(Context: SystemID: ' || v_systemid||', Company: '||v_company||', last_date: '||v_last_date

														||' Trace: '||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE, 

											P_CLOB => v_clob);

					END;

                END IF; -- IF v_count > 0 THEN

                --

                DBMS_OUTPUT.PUT_LINE(' HEADER CLE, Rows inserted: ' || v_insert_count|| ', updated: '||v_update_count);

                OMS.UTL_LOG.PR_INFO(g_execution_id, 'HEADER CLE, Rows inserted: ' || V_INSERT_COUNT ||', updated: '||V_UPDATE_COUNT );

                --

                COMMIT;

                --

                BEGIN

                    SELECT SUBSTR(NEXT_URL, INSTR(NEXT_URL, '?'))

                      INTO v_query

                    FROM JSON_TABLE

                        (

                        REPLACE(v_clob, '@', ''), '$'

                        COLUMNS

                            (

                            NEXT_URL VARCHAR2(4000) PATH '$."odata.nextLink"'

                            )

                        );

                    --

                EXCEPTION

                    WHEN NO_DATA_FOUND THEN

                        NULL;

                END;

                --

                EXIT WHEN v_query IS NULL;

                --

                IF v_query IS NOT NULL THEN

                    DBMS_OUTPUT.PUT_LINE(' HEADER CLE, Next Query String: ' || v_query);

                END IF;

                --

            END LOOP;

        END LOOP;

        --

    EXCEPTION

        WHEN OTHERS THEN

            RAISE_APPLICATION_ERROR

                (

                  -20001

                , 'HEADER CLE, Unexpected Error: '||SQLCODE||'-'||SQLERRM

                ||'(Context: SystemID: ' || v_systemid||', Company: '||v_company||', last_date: '||v_last_date||')'

                );

    END PR_LOAD_HEADERS;



    ----------------



    PROCEDURE MAIN_P(P_FULL_REFRESH IN CHAR DEFAULT 'N')

    AS

    BEGIN

        g_execution_id := OMS.UTL_LOG.FN_START

            (

              P_APP_ID       => 115                                                -- BC integration APP ID

            , P_OBJ_URI      => 'APPS_ORAFSYS.' || CONST_PACKAGE_NAME || '.MAIN_P'

            , P_TSK_CATEGORY => OMS.ADM_APP_TASKS_DAO.C_CAT_INTERFACE 

            , P_TSK_NAME     => 'Customer Ledger Entries Interface'

            );

        --

        PR_LOAD_HEADERS(P_FULL_REFRESH);

        PR_LOAD_DETAILS(P_FULL_REFRESH);

        --

        OMS.UTL_LOG.PR_SUCCESS(g_execution_id);

        --

        /* Post-process pending changes (Asynchronously) */

        OMS.BC_INV_SUMMARY_PKG.PR_POST_PROCESS_ASYNC(OMS.BC_INV_SUMMARY_PKG.CUSTOMER_LEDGER_ENTRIES);

        --

    EXCEPTION

        WHEN OTHERS THEN

            BEGIN

                APEX_MAIL.SEND

                    (

                      p_from => 'no-reply@ajcgroup.com'

                    , p_to   => 'lkusnier@ajcgroup.com, auhernandez@ajcgroup.com, itazelaar@ajcgroup.com'

                    , p_subj => 'Error on the integration of Customer Ledger Entries (Environment: '||g_environment||')'

                    , p_body => 'Error on the integration AJC_BC_AR_CLE_PKG.MAIN_P: '||sqlerrm

                             || ', Trace: '||DBMS_UTILITY.FORMAT_ERROR_BACKTRACE

                             || ', Check Execution ID:'||g_execution_id

                   );

                --

            EXCEPTION

                WHEN OTHERS THEN

                    NULL;

            END;

            --

            OMS.UTL_LOG.PR_FAILURE(g_execution_id, 'Execution failed: ' || SQLERRM);

            --

    END MAIN_P;



END AJC_BC_AR_CLE_PKG;
