
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APPS_ORAFSYS"."AJC_BC_GL_ORACLE_PERIOD_NUMS" ("PERIOD_NUM", "DESCRIPTION") AS 
  SELECT period_num,
         DECODE(period_num,1,'JAN',2,'FEB',3,'MAR',4,'APR',5,'MAY',6,'JUN',7,'JUL',8,'AUG',9,'SEP',10,'OCT',11,'NOV',12,'DEC',13,'ADJ',14,'AUD') description
    FROM gl_periods
   WHERE period_year BETWEEN 2021 AND 2024
GROUP BY period_num
ORDER BY period_num
