
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "APPS_ORAFSYS"."AJC_BC_GL_ORACLE_PERIOD_YEARS" ("PERIOD_YEAR") AS 
  SELECT period_year
    FROM gl_periods
   WHERE period_year BETWEEN 2021 AND 2024
GROUP BY period_year
ORDER BY period_year
