TRIGGER APPS_ORAFSYS.AJC_BC_ABBYY_INV_LINES
AFTER INSERT ON AJC.AJC_AP_ABBYY_INV_LINES_INT
REFERENCING
 NEW AS NEW
 OLD AS OLD
FOR EACH ROW DECLARE
BEGIN

   INSERT
     INTO AJC_BC_ABBYY_INV_LINES_INT
        (ORG_ID, VENDOR_ID, VENDOR_SITE_CODE, INVOICE_TYPE_LOOKUP_CODE, INVOICE_NUM, WORKSHEET_NUMBER, ACCRUAL_FUNC_AMOUNT, ACCRUAL_AMOUNT, REQUEST_ID, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, LINE_AMOUNT, SOURCE_TYPE, LINE_NUMBER)
    VALUES
        (:NEW.ORG_ID, :NEW.VENDOR_ID, :NEW.VENDOR_SITE_CODE, :NEW.INVOICE_TYPE_LOOKUP_CODE, :NEW.INVOICE_NUM, :NEW.WORKSHEET_NUMBER, :NEW.ACCRUAL_FUNC_AMOUNT, :NEW.ACCRUAL_AMOUNT, :NEW.REQUEST_ID, :NEW.CREATION_DATE, :NEW.CREATED_BY, :NEW.LAST_UPDATE_DATE, :NEW.LAST_UPDATED_BY, :NEW.LINE_AMOUNT, :NEW.SOURCE_TYPE, :NEW.LINE_NUMBER);
  
EXCEPTION
 WHEN OTHERS THEN
   NULL;
   
END;
