
  CREATE TABLE "APPS_ORAFSYS"."AJC_BC_ADAPTIVE_PERIOD_RATES" 
   (	"NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"CURRENCY_CODE" VARCHAR2(15) NOT NULL ENABLE, 
	"TO_CURRENCY_CODE" VARCHAR2(15) NOT NULL ENABLE, 
	"PERIOD_NAME" VARCHAR2(15) NOT NULL ENABLE, 
	"SHOW_AVG_RATE" NUMBER, 
	"SHOW_EOP_RATE" NUMBER, 
	"ERROR_MESSAGE" VARCHAR2(2000), 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"REQUEST_ID" NUMBER, 
	"PARENT_REQUEST_ID" NUMBER, 
	"PERIOD_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 
