
  CREATE TABLE "APPS_ORAFSYS"."AJC_BC_GL_DAILY_RATES_BKP" 
   (	"BC_COMPANY" VARCHAR2(100), 
	"FROM_CURRENCY" VARCHAR2(15) NOT NULL ENABLE, 
	"TO_CURRENCY" VARCHAR2(15) NOT NULL ENABLE, 
	"CONVERSION_DATE" DATE NOT NULL ENABLE, 
	"CONVERSION_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"CONVERSION_RATE" NUMBER NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER, 
	"STATUS" VARCHAR2(20), 
	"MESSAGE" VARCHAR2(2000), 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"LAST_UPDATE_LOGIN" NUMBER(15,0) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 
