
  CREATE TABLE "APPS_ORAFSYS"."AJC_BC_ADAPTIVE_AVG_RATES_UP" 
   (	"NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"CURRENCY_CODE" VARCHAR2(15), 
	"TO_CURRENCY_CODE" VARCHAR2(15), 
	"PERIOD_NAME" VARCHAR2(15), 
	"SHOW_AVG_RATE" NUMBER, 
	"SHOW_EOP_RATE" NUMBER, 
	"PERIOD_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" 
