
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "AJC"."AJC_BC_COMPANY_MAPPING_V" ("ORG_ID", "TK_ORG_COMPANY") AS 
  SELECT FV.ATTRIBUTE1 AS ORG_ID
     , CO.TK_ORG     AS TK_ORG_COMPANY
FROM HR_ORGANIZATION_UNITS OU
JOIN COMPANY               CO  ON CO.ORACLE_OPER_UNIT  = OU.NAME
JOIN FND_FLEX_VALUES       FV  ON FV.FLEX_VALUE        = CO.CO_GL_SUBACCT
                              AND FV.FLEX_VALUE_SET_ID = 1000001
WHERE CO.ALLOW_ORDERS = 'Y'
